# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Auth:   export LINODE_TOKEN=<token> (the provider reads it).
# Start:  terraform -chdir=.isoloom/cloud-vm/linode init && terraform -chdir=.isoloom/cloud-vm/linode apply \
#           -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/linode destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

variable "region" {
  type    = string
  default = "eu-central"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machines (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machines up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machines down after this many minutes (0: never)"
}

provider "linode" {}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-air-gapped-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
}

# The environment's one network: a VPC with a subnet at its exact range, so every machine keeps
# its address (192.168.62.0/24).
resource "linode_vpc" "env" {
  label  = local.name
  region = var.region
}

resource "linode_vpc_subnet" "env" {
  vpc_id = linode_vpc.env.id
  label  = "lab"
  ipv4   = "192.168.62.0/24"
}

resource "linode_firewall" "env" {
  label           = local.name
  inbound_policy  = "DROP"
  outbound_policy = "ACCEPT"
  inbound {
    label    = "ssh"
    action   = "ACCEPT"
    protocol = "TCP"
    ports    = "22"
    ipv4     = [var.allowed_cidr]
  }
  inbound {
    label    = "vpc-tcp"
    action   = "ACCEPT"
    protocol = "TCP"
    ports    = "1-65535"
    ipv4     = ["192.168.62.0/24"]
  }
  inbound {
    label    = "vpc-udp"
    action   = "ACCEPT"
    protocol = "UDP"
    ports    = "1-65535"
    ipv4     = ["192.168.62.0/24"]
  }
  inbound {
    label    = "vpc-icmp"
    action   = "ACCEPT"
    protocol = "ICMP"
    ipv4     = ["192.168.62.0/24"]
  }
  linodes = [linode_instance.store.id, linode_instance.app.id]
}

resource "random_password" "store" {
  length      = 24
  special     = false
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
}

resource "linode_instance" "store" {
  label           = "${local.name}-store"
  region          = var.region
  type            = "g6-nanode-1"
  image           = "linode/debian12"
  authorized_keys = [trimspace(var.ssh_public_key)]
  root_pass       = random_password.store.result
  booted          = true
  tags            = ["isoloom", "air-gapped"]
  metadata {
    user_data = base64encode(var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : "")
  }
  interface {
    purpose = "public"
  }
  interface {
    purpose   = "vpc"
    subnet_id = linode_vpc_subnet.env.id
    ipv4 {
      vpc = "192.168.62.20"
    }
  }
}

resource "terraform_data" "store" {
  triggers_replace = [linode_instance.store.id]
  connection {
    type        = "ssh"
    host        = one(linode_instance.store.ipv4)
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "command -v sudo >/dev/null || (apt-get update -qq && apt-get install -y -qq sudo)", "sudo mkdir -p /opt/isoloom && sudo chown root /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-store.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-store.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '192.168.62.10 app' | sudo tee -a /etc/hosts >/dev/null",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/store.sh'",
      "command -v nft >/dev/null || (sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nftables)",
      "printf '%s\\n' 'table inet isoloom-egress {' '  chain output {' '    type filter hook output priority 0; policy accept;' '    ip daddr != { 192.168.62.0/24 } ct state new drop' '  }' '}' | sudo tee /etc/isoloom-egress.nft >/dev/null && sudo nft -f /etc/isoloom-egress.nft",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [linode_firewall.env]
}

resource "random_password" "app" {
  length      = 24
  special     = false
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
}

resource "linode_instance" "app" {
  label           = "${local.name}-app"
  region          = var.region
  type            = "g6-nanode-1"
  image           = "linode/debian12"
  authorized_keys = [trimspace(var.ssh_public_key)]
  root_pass       = random_password.app.result
  booted          = true
  tags            = ["isoloom", "air-gapped"]
  metadata {
    user_data = base64encode(var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : "")
  }
  interface {
    purpose = "public"
  }
  interface {
    purpose   = "vpc"
    subnet_id = linode_vpc_subnet.env.id
    ipv4 {
      vpc = "192.168.62.10"
    }
  }
}

resource "terraform_data" "app" {
  triggers_replace = [linode_instance.app.id]
  connection {
    type        = "ssh"
    host        = one(linode_instance.app.ipv4)
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "command -v sudo >/dev/null || (apt-get update -qq && apt-get install -y -qq sudo)", "sudo mkdir -p /opt/isoloom && sudo chown root /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-app.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-app.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '192.168.62.20 store' | sudo tee -a /etc/hosts >/dev/null",
      "sh -c 'i=0; until (bash -c '\\''</dev/tcp/store/6379'\\'' 2>/dev/null || nc -z -w 2 store 6379 2>/dev/null); do i=$((i+2)); if [ $i -ge 900 ]; then echo \"store didn'\\''t answer within 900s\" >&2; exit 1; fi; sleep 2; done; echo \"store answers\"'",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/app.sh'",
      "command -v nft >/dev/null || (sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nftables)",
      "printf '%s\\n' 'table inet isoloom-egress {' '  chain output {' '    type filter hook output priority 0; policy accept;' '    ip daddr != { 192.168.62.0/24 } ct state new drop' '  }' '}' | sudo tee /etc/isoloom-egress.nft >/dev/null && sudo nft -f /etc/isoloom-egress.nft",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [linode_firewall.env, terraform_data.store]
}

output "machines" {
  value = {
    store = one(linode_instance.store.ipv4)
    app   = one(linode_instance.app.ipv4)
  }
}

output "ssh_users" {
  value = {
    store = "root"
    app   = "root"
  }
}

output "ip" {
  value = one(linode_instance.store.ipv4)
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}

# The checks: each runner on the machine it stands for (ssh <user>@<host> '<command>'), or `isoloom test cloud-vm`.
output "checks" {
  value = [
    { position = "store", machine = "store", host = one(linode_instance.store.ipv4), user = "root", command = "cd /opt/isoloom && sh .isoloom/cloud-vm/checks/store.sh" },
    { position = "app", machine = "app", host = one(linode_instance.app.ipv4), user = "root", command = "cd /opt/isoloom && sh .isoloom/cloud-vm/checks/app.sh" }
  ]
}
