#!/bin/sh
# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# The environment's checks, from user. `isoloom test` runs it and reads the PASS/FAIL lines.
passed=0; failed=0
pass() { passed=$((passed+1)); echo "isoloom-check: PASS $1"; }
fail() { failed=$((failed+1)); echo "isoloom-check: FAIL $1: $2"; }
# _http URL -> the status code, 000 when nothing answers (curl, else wget, else bash).
_http() {
  if command -v curl >/dev/null 2>&1; then
    c=$(curl -sk -o /dev/null -m 5 -w '%{http_code}' "$1" 2>/dev/null)
  elif command -v wget >/dev/null 2>&1; then
    c=$(wget -q -S -O /dev/null -T 5 --no-check-certificate "$1" 2>&1 | sed -n 's/^ *HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p' | tail -n 1)
  else
    u=${1#*://}; hp=${u%%/*}; p=/${u#*/}; [ "$u" = "$hp" ] && p=/
    h=${hp%%:*}; port=${hp#*:}; [ "$hp" = "$h" ] && port=80
    c=$(H=$h P=$port U=$p timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P && printf "GET %s HTTP/1.0\r\nHost: %s\r\n\r\n" "$U" "$H" >&3 && read -r l <&3 && echo "$l"' 2>/dev/null | sed -n 's/^HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p')
  fi
  echo "${c:-000}"
}
_http_is() { [ "$(_http "$1")" = "$2" ]; }
_http_any() { [ "$(_http "$1")" != 000 ]; }
# _tcp HOST PORT -> 0 when it connects (nc, else bash).
_tcp() {
  if command -v nc >/dev/null 2>&1; then nc -z -w 5 "$1" "$2" >/dev/null 2>&1
  else H=$1 P=$2 timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P' >/dev/null 2>&1
  fi
}
# _exec COMMAND TEXT -> 0 when the command succeeds and its output contains TEXT (if any).
_exec() { out=$(sh -c "$1" 2>&1) && { [ -z "$2" ] || printf '%s\n' "$out" | grep -qF -- "$2"; }; }
# _retry SECONDS COMMAND... -> keeps trying every 2s until it passes or the time is up.
_retry() { _end=$(( $(date +%s) + $1 )); shift; while ! "$@"; do [ "$(date +%s)" -lt "$_end" ] || return 1; sleep 2; done; }

echo '== checks/dmz-reachable.sh'
if _retry 0 sh -c 'cd /isoloom/project && sh checks/dmz-reachable.sh'; then pass 'checks/dmz-reachable.sh'; else fail 'checks/dmz-reachable.sh' "checks/dmz-reachable.sh exited non-zero"; fi

echo '== checks/internal-not-reachable-from-access.sh'
if _retry 0 sh -c 'cd /isoloom/project && sh checks/internal-not-reachable-from-access.sh'; then pass 'checks/internal-not-reachable-from-access.sh'; else fail 'checks/internal-not-reachable-from-access.sh' "checks/internal-not-reachable-from-access.sh exited non-zero"; fi

if [ "${ISOLOOM_DERIVED:-1}" != 0 ]; then
if _retry 30 _tcp '10.30.10.10' 80; then pass 'gateway:80 on dmz from user'; else fail 'gateway:80 on dmz from user' "nothing listens at 10.30.10.10:80"; fi
fi

if [ "${ISOLOOM_DERIVED:-1}" != 0 ]; then
if _retry 30 _tcp '10.30.10.10' 22; then pass 'gateway:22 on dmz from user'; else fail 'gateway:22 on dmz from user' "nothing listens at 10.30.10.10:22"; fi
fi

if [ "${ISOLOOM_DERIVED:-1}" != 0 ]; then
if _tcp '10.30.20.20' 8080; then fail 'app:8080 blocked from user' "10.30.20.20:8080 answered; it should be blocked"; else pass 'app:8080 blocked from user'; fi
fi

if [ "${ISOLOOM_DERIVED:-1}" != 0 ]; then
if _tcp '10.30.20.30' 5432; then fail 'db:5432 blocked from user' "10.30.20.30:5432 answered; it should be blocked"; else pass 'db:5432 blocked from user'; fi
fi

echo "isoloom-check: END $passed passed, $failed failed"
[ "$failed" -eq 0 ]
