#!/bin/sh
# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# The environment's checks, from web. `isoloom test` runs it and reads the PASS/FAIL lines.
passed=0; failed=0
pass() { passed=$((passed+1)); echo "isoloom-check: PASS $1"; }
fail() { failed=$((failed+1)); echo "isoloom-check: FAIL $1: $2"; }
# _http URL -> the status code, 000 when nothing answers (curl, else wget, else bash).
_http() {
  if command -v curl >/dev/null 2>&1; then
    c=$(curl -sk -o /dev/null -m 5 -w '%{http_code}' "$1" 2>/dev/null)
  elif command -v wget >/dev/null 2>&1; then
    c=$(wget -q -S -O /dev/null -T 5 --no-check-certificate "$1" 2>&1 | sed -n 's/^ *HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p' | tail -n 1)
  else
    u=${1#*://}; hp=${u%%/*}; p=/${u#*/}; [ "$u" = "$hp" ] && p=/
    h=${hp%%:*}; port=${hp#*:}; [ "$hp" = "$h" ] && port=80
    c=$(H=$h P=$port U=$p timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P && printf "GET %s HTTP/1.0\r\nHost: %s\r\n\r\n" "$U" "$H" >&3 && read -r l <&3 && echo "$l"' 2>/dev/null | sed -n 's/^HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p')
  fi
  echo "${c:-000}"
}
_http_is() { [ "$(_http "$1")" = "$2" ]; }
# _req STATUS|any TEXT CURL-ARGS... -> 0 when the request gets that status (any answer for `any`)
# and its body contains TEXT (if any); $out says why not. Needs curl.
_req() {
  want=$1; text=$2; shift 2
  command -v curl >/dev/null 2>&1 || { out="curl is needed for this check"; return 1; }
  b=$(mktemp); c=$(curl -sk -m 10 -o "$b" -w '%{http_code}' "$@" 2>/dev/null); c=${c:-000}; r=0
  if [ "$want" = any ]; then [ "$c" != 000 ] || r=1; else [ "$c" = "$want" ] || r=1; fi
  if [ $r = 1 ]; then out="expected HTTP $want, got $c"
  elif [ -n "$text" ] && ! grep -qF -- "$text" "$b"; then r=1; out="HTTP $c, but the response doesn't contain the expected text"
  fi
  rm -f "$b"; return $r
}
_http_any() { [ "$(_http "$1")" != 000 ]; }
# _tcp HOST PORT -> 0 when it connects (nc, else bash).
_tcp() {
  if command -v nc >/dev/null 2>&1; then nc -z -w 5 "$1" "$2" >/dev/null 2>&1
  else H=$1 P=$2 timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P' >/dev/null 2>&1
  fi
}
# _tcp_read HOST PORT LINE TEXT -> 0 when the bytes read within 5s of connecting (after writing
# LINE and a newline, if any) contain TEXT; $out says why not (nc, else bash). Stdin stays open
# while reading (some nc quit at its end), and nc is stopped after 5s whatever its flavor.
_tcp_read() {
  f=$(mktemp); i=0; r=1
  if command -v nc >/dev/null 2>&1; then
    { [ -z "$3" ] || printf '%s\n' "$3"; j=0; while [ ! -e "$f.end" ] && [ $j -lt 6 ]; do sleep 1; j=$((j+1)); done; } | nc "$1" "$2" >"$f" 2>/dev/null &
  else
    H=$1 P=$2 L=$3 timeout 6 bash -c 'exec 3<>/dev/tcp/$H/$P || exit 1; [ -z "$L" ] || printf "%s\n" "$L" >&3; cat <&3' >"$f" 2>/dev/null &
  fi
  p=$!
  while :; do
    if grep -qF -- "$4" "$f"; then r=0; break; fi
    [ $i -lt 5 ] && kill -0 $p 2>/dev/null || break
    sleep 1; i=$((i+1))
  done
  [ $r = 0 ] || ! grep -qF -- "$4" "$f" || r=0
  touch "$f.end"; kill $p 2>/dev/null
  if [ $r = 1 ]; then
    if [ -s "$f" ]; then out="$1:$2 answered \"$(head -c 100 "$f" | tr -d '\000\r' | tr '\n\t' '  ')\", without the expected text"
    elif [ $i -lt 5 ]; then out="$1:$2 refused the connection or closed it without a word"
    else out="nothing read from $1:$2 within 5s"; fi
  fi
  rm -f "$f" "$f.end"; return $r
}
# _exec COMMAND TEXT -> 0 when the command succeeds and its output contains TEXT (if any).
_exec() { out=$(sh -c "$1" 2>&1) && { [ -z "$2" ] || printf '%s\n' "$out" | grep -qF -- "$2"; }; }
# _retry SECONDS COMMAND... -> keeps trying every 2s until it passes or the time is up.
_retry() { _end=$(( $(date +%s) + $1 )); shift; while ! "$@"; do [ "$(date +%s)" -lt "$_end" ] || return 1; sleep 2; done; }

if [ "${ISOLOOM_DERIVED:-1}" != 0 ]; then
if _retry 30 _tcp '10.61.20.20' 6379; then pass 'cache:6379 from web'; else fail 'cache:6379 from web' "nothing listens at 10.61.20.20:6379"; fi
fi

echo "isoloom-check: END $passed passed, $failed failed"
[ "$failed" -eq 0 ]
