# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/proxmox init && terraform -chdir=.isoloom/proxmox apply -var proxmox_endpoint=https://<server>:8006/ -var proxmox_api_token=<user@realm!name=secret>
# Stop:   terraform -chdir=.isoloom/proxmox destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.115"
    }
    # The controller's SSH key (environment-level provisioning).
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

variable "proxmox_endpoint" {
  type        = string
  description = "https://<server>:8006/"
}
variable "proxmox_api_token" {
  type        = string
  default     = ""
  sensitive   = true
  description = "user@realm!name=secret; or use proxmox_username and proxmox_password"
}
variable "proxmox_username" {
  type    = string
  default = "root@pam"
}
variable "proxmox_password" {
  type      = string
  default   = ""
  sensitive = true
}
variable "proxmox_insecure" {
  type        = bool
  default     = true
  description = "Accept the server's self-signed certificate"
}
variable "proxmox_ssh_username" {
  type        = string
  default     = "root"
  description = "Uploading cloud-init snippets goes over SSH to the node"
}
variable "proxmox_ssh_private_key_file" {
  type    = string
  default = ""
}
variable "proxmox_ssh_address" {
  type        = string
  default     = ""
  description = "The node's SSH address, when the API reports one this machine can't reach"
}
variable "node" {
  type    = string
  default = "pve"
}
variable "datastore" {
  type        = string
  default     = "local-lvm"
  description = "Where VM disks go"
}
variable "image_datastore" {
  type        = string
  default     = "local"
  description = "A datastore with 'iso' content, for cloud images"
}
variable "snippets_datastore" {
  type        = string
  default     = "local"
  description = "A datastore with 'snippets' content, for cloud-init"
}
variable "uplink_bridge" {
  type        = string
  default     = "vmbr0"
  description = "The bridge the router reaches the internet through"
}
variable "slot" {
  type        = number
  default     = 1
  description = "1 to 99, unique per environment on this server (SDN ids are short)"
}
variable "ssh_public_key" {
  type        = string
  default     = ""
  description = "Installed for the user `isoloom` on every VM"
}

provider "proxmox" {
  endpoint  = var.proxmox_endpoint
  api_token = var.proxmox_api_token != "" ? var.proxmox_api_token : null
  username  = var.proxmox_api_token != "" ? null : var.proxmox_username
  password  = var.proxmox_api_token != "" ? null : var.proxmox_password
  insecure  = var.proxmox_insecure
  ssh {
    agent       = false
    username    = var.proxmox_ssh_username
    password    = var.proxmox_ssh_private_key_file != "" ? null : var.proxmox_password
    private_key = var.proxmox_ssh_private_key_file != "" ? file(var.proxmox_ssh_private_key_file) : null
    dynamic "node" {
      for_each = var.proxmox_ssh_address == "" ? [] : [1]
      content {
        name    = var.node
        address = var.proxmox_ssh_address
      }
    }
  }
}

locals {
  zone = "iso${var.slot}"
  # The project, written to /opt/isoloom in each machine that has steps.
  root = abspath("${path.module}/../..")
  project_files = [for f in local.project_paths : {
    path     = "/opt/isoloom/${f}"
    encoding = "b64"
    content  = filebase64("${local.root}/${f}")
  }]
  users = [{
    name                = "isoloom"
    sudo                = "ALL=(ALL) NOPASSWD:ALL"
    shell               = "/bin/bash"
    ssh_authorized_keys = compact([var.ssh_public_key, trimspace(tls_private_key.controller.public_key_openssh)])
  }]
}

# The environment's networks: an SDN simple zone, a VNet per network.
resource "proxmox_sdn_zone_simple" "env" {
  id    = local.zone
  nodes = [var.node]
}

# The controller's own key: it runs the playbooks over SSH on every machine.
resource "tls_private_key" "controller" {
  algorithm = "ED25519"
}

# Network `lab`: 10.63.0.0/24
resource "proxmox_sdn_vnet" "lab" {
  id   = "i${var.slot}n0"
  zone = proxmox_sdn_zone_simple.env.id
}

resource "proxmox_sdn_applier" "env" {
  depends_on = [proxmox_sdn_vnet.lab]
}

resource "proxmox_download_file" "debian_12" {
  node_name    = var.node
  datastore_id = var.image_datastore
  content_type = "iso"
  url          = "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"
  # Per environment: a shared file would go with whichever environment is destroyed first.
  file_name           = "iso${var.slot}-debian-12.img"
  overwrite_unmanaged = true
}

# The router: forwards between networks with the reach rules, and to the internet.
resource "proxmox_virtual_environment_file" "router" {
  node_name    = var.node
  datastore_id = var.snippets_datastore
  content_type = "snippets"
  source_raw {
    file_name = "iso${var.slot}-router.yaml"
    data = "#cloud-config\n${yamlencode({
      hostname = "isoloom-router"
      users    = local.users
      packages = ["nftables", "qemu-guest-agent"]
      write_files = [
        { path = "/etc/systemd/network/10-wan.network", content = join("\n", ["[Match]", "MACAddress=${format("02:15:%02x:00:00:00", var.slot)}", "", "[Network]", "DHCP=yes"]) },
        { path = "/etc/nftables.conf", content = "flush ruleset\ntable inet isoloom {\n  chain forward {\n    type filter hook forward priority 0; policy drop;\n    ct state established,related accept\n    ip saddr { 10.63.0.0/24 } ip daddr != { 10.63.0.0/24 } accept\n  }\n  chain prerouting {\n    type nat hook prerouting priority -100;\n  }\n  chain postrouting {\n    type nat hook postrouting priority 100;\n    ip saddr { 10.63.0.0/24 } ip daddr != { 10.63.0.0/24 } masquerade\n  }\n}\n" },
        { path = "/etc/sysctl.d/90-isoloom.conf", content = "net.ipv4.ip_forward=1\n" },
        { path = "/etc/systemd/network/20-lab.network", content = join("\n", ["[Match]", "MACAddress=${format("02:15:%02x:01:%02x:00", var.slot, 0)}", "", "[Network]", "Address=10.63.0.254/24", "ConfigureWithoutCarrier=yes"]) }
      ]
      runcmd = [
        ["sysctl", "-p", "/etc/sysctl.d/90-isoloom.conf"],
        ["systemctl", "enable", "systemd-networkd"],
        ["systemctl", "restart", "systemd-networkd"],
        ["systemctl", "enable", "--now", "nftables"],
        ["nft", "-f", "/etc/nftables.conf"],
        ["systemctl", "enable", "--now", "qemu-guest-agent"],
      ]
    })}"
  }
}

resource "proxmox_virtual_environment_vm" "isoloom_router" {
  name      = "iso${var.slot}-router"
  node_name = var.node
  tags      = ["isoloom", "ansible-pair"]
  on_boot   = false
  # Its uplink address (DHCP), for the published ports.
  agent {
    enabled = true
  }
  cpu {
    cores = 1
    type  = "host"
  }
  memory {
    dedicated = 512
  }
  disk {
    datastore_id = var.datastore
    file_id      = proxmox_download_file.debian_12.id
    interface    = "virtio0"
    size         = 8
  }
  network_device {
    bridge      = var.uplink_bridge
    mac_address = upper(format("02:15:%02x:00:00:00", var.slot))
  }
  network_device {
    bridge      = proxmox_sdn_vnet.lab.id
    mac_address = upper(format("02:15:%02x:01:%02x:00", var.slot, 0))
  }
  initialization {
    datastore_id      = var.datastore
    user_data_file_id = proxmox_virtual_environment_file.router.id
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }
  operating_system {
    type = "l26"
  }
  serial_device {}
  depends_on = [proxmox_sdn_applier.env]
}

# Machine `web`.
resource "proxmox_virtual_environment_file" "web" {
  node_name    = var.node
  datastore_id = var.snippets_datastore
  content_type = "snippets"
  source_raw {
    file_name = "iso${var.slot}-web.yaml"
    data = "#cloud-config\n${yamlencode({
      hostname    = "web"
      users       = local.users
      packages    = ["nftables", "curl", "netcat-openbsd"]
      write_files = []
      runcmd = [
        ["sh", "-c", "printf '%s\\n' '10.63.0.20 cache' >> /etc/hosts"],
        ["sh", "-c", "mkdir -p /var/lib/isoloom && echo ready > /var/lib/isoloom/ready"]
      ]
    })}"
  }
}

resource "proxmox_virtual_environment_vm" "web" {
  name      = "iso${var.slot}-web"
  node_name = var.node
  tags      = ["isoloom", "ansible-pair"]
  on_boot   = false
  cpu {
    cores = 1
    type  = "host"
  }
  memory {
    dedicated = 1024
  }
  disk {
    datastore_id = var.datastore
    file_id      = proxmox_download_file.debian_12.id
    interface    = "virtio0"
    size         = 20
  }
  network_device {
    bridge = proxmox_sdn_vnet.lab.id
  }
  initialization {
    datastore_id      = var.datastore
    user_data_file_id = proxmox_virtual_environment_file.web.id
    dns {
      servers = ["1.1.1.1"]
    }
    ip_config {
      ipv4 {
        address = "10.63.0.10/24"
        gateway = "10.63.0.254"
      }
    }
  }
  operating_system {
    type = "l26"
  }
  serial_device {}
  depends_on = [proxmox_virtual_environment_vm.isoloom_router]
}

# Machine `cache`.
resource "proxmox_virtual_environment_file" "cache" {
  node_name    = var.node
  datastore_id = var.snippets_datastore
  content_type = "snippets"
  source_raw {
    file_name = "iso${var.slot}-cache.yaml"
    data = "#cloud-config\n${yamlencode({
      hostname    = "cache"
      users       = local.users
      packages    = ["nftables", "curl", "netcat-openbsd"]
      write_files = []
      runcmd = [
        ["sh", "-c", "printf '%s\\n' '10.63.0.10 web' >> /etc/hosts"],
        ["sh", "-c", "mkdir -p /var/lib/isoloom && echo ready > /var/lib/isoloom/ready"]
      ]
    })}"
  }
}

resource "proxmox_virtual_environment_vm" "cache" {
  name      = "iso${var.slot}-cache"
  node_name = var.node
  tags      = ["isoloom", "ansible-pair"]
  on_boot   = false
  cpu {
    cores = 1
    type  = "host"
  }
  memory {
    dedicated = 1024
  }
  disk {
    datastore_id = var.datastore
    file_id      = proxmox_download_file.debian_12.id
    interface    = "virtio0"
    size         = 20
  }
  network_device {
    bridge = proxmox_sdn_vnet.lab.id
  }
  initialization {
    datastore_id      = var.datastore
    user_data_file_id = proxmox_virtual_environment_file.cache.id
    dns {
      servers = ["1.1.1.1"]
    }
    ip_config {
      ipv4 {
        address = "10.63.0.20/24"
        gateway = "10.63.0.254"
      }
    }
  }
  operating_system {
    type = "l26"
  }
  serial_device {}
  depends_on = [proxmox_virtual_environment_vm.isoloom_router]
}

# The controller: runs the environment's playbooks once every machine is up.
resource "proxmox_virtual_environment_file" "controller" {
  node_name    = var.node
  datastore_id = var.snippets_datastore
  content_type = "snippets"
  source_raw {
    file_name = "iso${var.slot}-controller.yaml"
    data = "#cloud-config\n${yamlencode({
      hostname    = "isoloom-controller"
      users       = local.users
      packages    = ["python3-venv", "curl", "netcat-openbsd", "openssh-client"]
      write_files = concat(local.project_files, [{ path = "/etc/isoloom/id_ed25519", permissions = "0600", content = tls_private_key.controller.private_key_openssh }, { path = "/etc/isoloom/inventory.ini", permissions = "0644", content = "[linux]\nweb ansible_host=10.63.0.10 ansible_user=isoloom\ncache ansible_host=10.63.0.20 ansible_user=isoloom\n\n[windows]\n\n[linux:vars]\nansible_ssh_private_key_file=/etc/isoloom/id_ed25519\nansible_become=true\n\n[webservers]\nweb\n\n[caches]\ncache\n" }])
      runcmd = [
        ["sh", "-c", "printf '%s\\n' '10.63.0.10 web' '10.63.0.20 cache' >> /etc/hosts"],
        ["sh", "-c", "python3 -m venv /opt/ansible && /opt/ansible/bin/pip install -q 'ansible-core>=2.15,<2.17' pywinrm"],
        ["sh", "-c", "i=0; until ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /etc/isoloom/id_ed25519 isoloom@10.63.0.10 test -f /var/lib/isoloom/ready 2>/dev/null; do i=$((i+1)); [ $i -gt 240 ] && { echo 'web not ready'; exit 1; }; sleep 5; done"],
        ["sh", "-c", "i=0; until ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /etc/isoloom/id_ed25519 isoloom@10.63.0.20 test -f /var/lib/isoloom/ready 2>/dev/null; do i=$((i+1)); [ $i -gt 240 ] && { echo 'cache not ready'; exit 1; }; sleep 5; done"],
        ["sh", "-c", "sh -c 'set -e\nmkdir -p /tmp/isoloom-facts\nexport PATH=/opt/ansible/bin:$PATH ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_GATHERING=smart ANSIBLE_FORKS=20 ANSIBLE_PIPELINING=True ANSIBLE_CACHE_PLUGIN=jsonfile ANSIBLE_CACHE_PLUGIN_CONNECTION=/tmp/isoloom-facts ANSIBLE_CACHE_PLUGIN_TIMEOUT=7200\ncd /opt/isoloom/ansible\nansible-galaxy install -r /opt/isoloom/ansible/requirements.yml\nansible-playbook -i /etc/isoloom/inventory.ini -i /opt/isoloom/ansible/groups.ini -e '\\''{\"greeting\":\"hello from ansible\"}'\\'' site.yml\n'"],
        ["sh", "-c", "mkdir -p /var/lib/isoloom && echo ready > /var/lib/isoloom/ready"]
      ]
    })}"
  }
}

resource "proxmox_virtual_environment_vm" "isoloom_controller" {
  name      = "iso${var.slot}-controller"
  node_name = var.node
  tags      = ["isoloom", "ansible-pair"]
  on_boot   = false
  cpu {
    cores = 1
    type  = "host"
  }
  memory {
    dedicated = 1024
  }
  disk {
    datastore_id = var.datastore
    file_id      = proxmox_download_file.debian_12.id
    interface    = "virtio0"
    size         = 8
  }
  network_device {
    bridge = var.uplink_bridge
  }
  network_device {
    bridge = proxmox_sdn_vnet.lab.id
  }
  initialization {
    datastore_id      = var.datastore
    user_data_file_id = proxmox_virtual_environment_file.controller.id
    dns {
      servers = ["1.1.1.1"]
    }
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    ip_config {
      ipv4 {
        address = "10.63.0.253/24"
      }
    }
  }
  operating_system {
    type = "l26"
  }
  serial_device {}
  depends_on = [proxmox_virtual_environment_vm.isoloom_router, proxmox_virtual_environment_vm.web, proxmox_virtual_environment_vm.cache]
}

locals {
  router_address = [for a in flatten(proxmox_virtual_environment_vm.isoloom_router.ipv4_addresses) : a if a != "127.0.0.1" && !contains(["10.63.0.254"], a)][0]
}

output "address" {
  value = local.router_address
}

# The machines, through the router: ssh -J isoloom@<address> isoloom@<machine>.
output "machines" {
  value = {
    "web"   = "10.63.0.10"
    "cache" = "10.63.0.20"
  }
}

output "ssh_user" {
  value = "isoloom"
}

# The checks: each runner piped to its machine (ssh -J isoloom@<address> isoloom@<host> sh -s < <script>), or `isoloom test proxmox`.
output "checks" {
  value = [
    { position = "networks", machine = "controller", host = "10.63.0.253", user = "isoloom", script = ".isoloom/proxmox/checks/networks.sh" },
    { position = "web", machine = "web", host = "10.63.0.10", user = "isoloom", script = ".isoloom/proxmox/checks/web.sh" },
    { position = "cache", machine = "cache", host = "10.63.0.20", user = "isoloom", script = ".isoloom/proxmox/checks/cache.sh" }
  ]
}

# The project's files the machines don't get: version control and the tools' state, and what
# .isoloomignore at the project's root lists (gitignore-style: one pattern per line, `#` comments,
# `!` brings a path back, a trailing `/` matches folders only, a `/` at the start or in the middle
# anchors the pattern at the root; `*`, `?`, `[abc]`, `**`; the last pattern matching a path, or
# a folder it is in, decides). Read as regular expressions, as the Vagrantfiles do.
locals {
  project_ignore_lines = [for l in split("\n", replace(try(file("${local.root}/.isoloomignore"), ""), "\r", "")) : trimspace(l)]
  project_ignore_pats  = [for l in local.project_ignore_lines : { keep = startswith(l, "!"), pat = trimprefix(l, "!") } if l != "" && !startswith(l, "#")]
  project_ignore_globs = [for r in local.project_ignore_pats : merge(r, { glob = trimsuffix(trimsuffix(trimsuffix(r.pat, "/"), "/**"), "/") })]
  project_ignore = [for r in local.project_ignore_globs : {
    keep = r.keep
    re = format(r.glob == r.pat ? "^%s(/|$)" : "^%s/", replace(replace(replace(replace(replace(replace(replace(replace(
      length(split("/", r.glob)) > 1 ? trimprefix(r.glob, "/") : "**/${r.glob}",
    "/[.+^$(){}|\\\\]/", "\\$0"), "[!", "[^"), "**/", "\u0001"), "**", "\u0002"), "*", "[^/]*"), "?", "[^/]"), "\u0001", "(.*/)?"), "\u0002", ".*"))
  } if r.glob != ""]
  # Each file: whether it goes (the last matching pattern decides; none: it goes).
  project_keep    = { for f in fileset(local.root, "**") : f => reverse(concat([true], [for r in local.project_ignore : r.keep if length(regexall(r.re, f)) > 0]))[0] }
  project_paths   = [for f, keep in local.project_keep : f if keep && length(regexall("^\\.isoloom|(^|/)\\.(git|vagrant|terraform)/", f)) == 0]
  project_ignored = [for f, keep in local.project_keep : f if !keep]
}
