//! Pictures and tables of an environment, from the resolved snapshot: `isoloom graph` draws
//! the networks, machines, reach rules and gateways (D2 or Graphviz; SVG/PNG when the renderer
//! is installed); `isoloom report` prints addressing, services, wiring and resources as text or
//! Markdown. Both read what [`crate::resolved::resolve`] worked out, so they can't disagree
//! with the generated files.

use std::fmt::Write;

use serde_json::Value;

/// The graph as D2 (<https://d2lang.com>): networks as hexagons, machines as boxes (the
/// access machine as a person, gateways as diamonds), membership edges labeled with the last
/// octet, `reach` as dashed arrows between networks labeled with their ports.
pub fn graph_d2(r: &Value) -> String {
    let mut out = String::new();
    let name = r["name"].as_str().unwrap_or("environment");
    let _ = writeln!(out, "# {name}: generated by isoloom graph. Render: d2 {name}.d2 {name}.svg");
    let _ = writeln!(out, "direction: right\n");
    for (net, n) in r["networks"].as_object().into_iter().flatten() {
        let mut label = format!("{net}\\n{}", n["cidr"].as_str().unwrap_or(""));
        if n["internet"].as_bool() == Some(false) {
            label.push_str("\\nno internet");
        }
        let _ = writeln!(out, "net_{}: \"{label}\" {{ shape: hexagon }}", id(net));
    }
    out.push('\n');
    for (m, v) in r["machines"].as_object().into_iter().flatten() {
        let mut label = m.to_string();
        let services: Vec<String> = v["services"]
            .as_array()
            .into_iter()
            .flatten()
            .map(|s| match s["name"].as_str() {
                Some(n) => format!("{} {n}", s["port"]),
                None => s["port"].to_string(),
            })
            .collect();
        if !services.is_empty() {
            label.push_str("\\n");
            label.push_str(&services.join(", "));
        }
        let shape = if v["access"].as_bool() == Some(true) {
            "person"
        } else if v["gateway_of"].as_array().is_some_and(|g| !g.is_empty()) {
            "diamond"
        } else {
            "rectangle"
        };
        let _ = writeln!(out, "m_{}: \"{label}\" {{ shape: {shape} }}", id(m));
        for (net, addr) in v["addresses"].as_object().into_iter().flatten() {
            let octet = addr.as_str().and_then(|a| a.rsplit('.').next()).unwrap_or("");
            let _ = writeln!(out, "m_{} -- net_{}: \".{octet}\"", id(m), id(net));
        }
    }
    if let Some(router) = r["router"].as_object() {
        let _ = writeln!(out, "\nrouter: \"router\\n(reach rules)\" {{ shape: cylinder }}");
        for net in router["networks"].as_array().into_iter().flatten().filter_map(Value::as_str) {
            let _ = writeln!(out, "router -- net_{}", id(net));
        }
    }
    if let Some(reach) = r["reach"].as_array().filter(|a| !a.is_empty()) {
        out.push('\n');
        for rule in reach {
            let (from, to) = (rule["from"].as_str().unwrap_or(""), rule["to"].as_str().unwrap_or(""));
            let ports: Vec<String> = rule["ports"].as_array().into_iter().flatten().map(Value::to_string).collect();
            let label = if ports.is_empty() { "all ports".to_string() } else { ports.join(", ") };
            let _ = writeln!(out, "net_{} -> net_{}: \"{label}\" {{ style.stroke-dash: 3 }}", id(from), id(to));
        }
    }
    out
}

/// The graph as Graphviz DOT. Render: `dot -Tsvg -o name.svg name.dot`.
pub fn graph_dot(r: &Value) -> String {
    let mut out = String::new();
    let name = r["name"].as_str().unwrap_or("environment");
    let _ = writeln!(out, "// {name}: generated by isoloom graph. Render: dot -Tsvg -o {name}.svg {name}.dot");
    let _ = writeln!(
        out,
        "digraph \"{name}\" {{\n  rankdir=LR;\n  node [fontname=\"Helvetica\", fontsize=10];\n  edge [fontname=\"Helvetica\", fontsize=9];"
    );
    for (net, n) in r["networks"].as_object().into_iter().flatten() {
        let mut label = format!("{net}\\n{}", n["cidr"].as_str().unwrap_or(""));
        if n["internet"].as_bool() == Some(false) {
            label.push_str("\\nno internet");
        }
        let _ = writeln!(
            out,
            "  net_{} [label=\"{label}\", shape=hexagon, style=filled, fillcolor=\"#eeeeee\"];",
            id(net)
        );
    }
    for (m, v) in r["machines"].as_object().into_iter().flatten() {
        let mut label = m.to_string();
        let services: Vec<String> = v["services"].as_array().into_iter().flatten().map(|s| s["port"].to_string()).collect();
        if !services.is_empty() {
            label.push_str(&format!("\\n:{}", services.join(" :")));
        }
        let shape = if v["access"].as_bool() == Some(true) {
            "egg"
        } else if v["gateway_of"].as_array().is_some_and(|g| !g.is_empty()) {
            "diamond"
        } else {
            "box"
        };
        let _ = writeln!(out, "  m_{} [label=\"{label}\", shape={shape}];", id(m));
        for (net, addr) in v["addresses"].as_object().into_iter().flatten() {
            let octet = addr.as_str().and_then(|a| a.rsplit('.').next()).unwrap_or("");
            let _ = writeln!(out, "  m_{} -> net_{} [label=\".{octet}\", dir=none];", id(m), id(net));
        }
    }
    if let Some(router) = r["router"].as_object() {
        let _ = writeln!(out, "  router [label=\"router\\n(reach rules)\", shape=cylinder];");
        for net in router["networks"].as_array().into_iter().flatten().filter_map(Value::as_str) {
            let _ = writeln!(out, "  router -> net_{} [dir=none];", id(net));
        }
    }
    for rule in r["reach"].as_array().into_iter().flatten() {
        let (from, to) = (rule["from"].as_str().unwrap_or(""), rule["to"].as_str().unwrap_or(""));
        let ports: Vec<String> = rule["ports"].as_array().into_iter().flatten().map(Value::to_string).collect();
        let label = if ports.is_empty() { "all ports".to_string() } else { ports.join(", ") };
        let _ = writeln!(
            out,
            "  net_{} -> net_{} [label=\"{label}\", style=dashed, color=\"#555555\"];",
            id(from),
            id(to)
        );
    }
    out.push_str("}\n");
    out
}

/// A name as a D2/DOT identifier.
fn id(name: &str) -> String {
    name.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect()
}

/// The reports `isoloom report` knows.
pub const REPORTS: &[(&str, &str)] = &[
    ("addressing", "every machine's address on every network"),
    ("services", "what answers on which port, and from which networks it may be reached"),
    (
        "wiring",
        "how each target lays the networks out: Docker blocks, VirtualBox and libvirt network names, Kubernetes labels",
    ),
    ("resources", "CPUs, memory and disk per machine, and the totals"),
];

/// One report, as text (aligned columns) or Markdown.
pub fn report(name: &str, r: &Value, markdown: bool) -> Result<String, String> {
    let (head, rows) = match name {
        "addressing" => addressing(r),
        "services" => services(r),
        "wiring" => wiring(r),
        "resources" => resources(r),
        other => {
            return Err(format!(
                "no report named `{other}`; one of: {}",
                REPORTS.iter().map(|(n, _)| *n).collect::<Vec<_>>().join(", ")
            ));
        }
    };
    Ok(table(&head, &rows, markdown))
}

fn addressing(r: &Value) -> (Vec<String>, Vec<Vec<String>>) {
    let nets: Vec<String> = r["networks"].as_object().into_iter().flatten().map(|(n, _)| n.clone()).collect();
    let mut head = vec!["machine".to_string()];
    head.extend(nets.iter().cloned());
    let mut rows = Vec::new();
    for (m, v) in r["machines"].as_object().into_iter().flatten() {
        let mut row = vec![m.clone()];
        for n in &nets {
            row.push(v["addresses"][n].as_str().unwrap_or("").to_string());
        }
        rows.push(row);
    }
    if let Some(router) = r["router"].as_object() {
        let mut row = vec!["(router)".to_string()];
        for n in &nets {
            row.push(router["addresses"][n].as_str().unwrap_or("").to_string());
        }
        rows.push(row);
    }
    (head, rows)
}

fn services(r: &Value) -> (Vec<String>, Vec<Vec<String>>) {
    let head = ["machine", "port", "name", "http", "published", "reachable from"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    let mut rows = Vec::new();
    let nets: Vec<String> = r["networks"].as_object().into_iter().flatten().map(|(n, _)| n.clone()).collect();
    for (m, v) in r["machines"].as_object().into_iter().flatten() {
        let own: Vec<&str> = v["addresses"].as_object().into_iter().flatten().map(|(n, _)| n.as_str()).collect();
        for s in v["services"].as_array().into_iter().flatten() {
            let port = s["port"].as_u64().unwrap_or(0);
            let mut from: Vec<String> = Vec::new();
            for n in &nets {
                let allowed = own.contains(&n.as_str())
                    || r["reach"].as_array().into_iter().flatten().any(|rule| {
                        rule["from"].as_str() == Some(n.as_str())
                            && own.contains(&rule["to"].as_str().unwrap_or(""))
                            && rule["ports"]
                                .as_array()
                                .is_some_and(|p| p.is_empty() || p.iter().any(|x| x.as_u64() == Some(port)))
                    });
                if allowed {
                    from.push(n.clone());
                }
            }
            rows.push(vec![
                m.clone(),
                port.to_string(),
                s["name"].as_str().unwrap_or("").to_string(),
                if s["http"].as_bool() == Some(true) { "yes".into() } else { String::new() },
                s["publish"].as_u64().map(|p| format!("127.0.0.1:{p}")).unwrap_or_default(),
                from.join(", "),
            ]);
        }
    }
    (head, rows)
}

fn wiring(r: &Value) -> (Vec<String>, Vec<Vec<String>>) {
    let name = r["name"].as_str().unwrap_or("");
    let head = [
        "network",
        "cidr",
        "docker block",
        "virtualbox / libvirt network",
        "kubernetes label",
        "gateway",
        "router",
        "internet",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect();
    let rows = r["networks"]
        .as_object()
        .into_iter()
        .flatten()
        .map(|(n, v)| {
            vec![
                n.clone(),
                v["cidr"].as_str().unwrap_or("").to_string(),
                v["docker_cidr"].as_str().unwrap_or("").to_string(),
                format!("isoloom-{name}-{n}"),
                format!("net.isoloom.com/{n}=member"),
                v["gateway"]
                    .as_str()
                    .map(|g| format!("{g} ({})", v["gateway_address"].as_str().unwrap_or("")))
                    .unwrap_or_default(),
                v["router"].as_str().unwrap_or("").to_string(),
                if v["internet"].as_bool() == Some(false) { "no".into() } else { "yes".into() },
            ]
        })
        .collect();
    (head, rows)
}

fn resources(r: &Value) -> (Vec<String>, Vec<Vec<String>>) {
    let head = ["machine", "cpus", "memory (MB)", "disk (GB)", "os", "shapes"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    let mut rows = Vec::new();
    let (mut c, mut m, mut d) = (0u64, 0u64, 0u64);
    for (name, v) in r["machines"].as_object().into_iter().flatten() {
        let res = &v["resources"];
        let (cpus, mem, disk) = (
            res["cpus"].as_u64().unwrap_or(0),
            res["memory_mb"].as_u64().unwrap_or(0),
            res["disk_gb"].as_u64().unwrap_or(0),
        );
        c += cpus;
        m += mem;
        d += disk;
        rows.push(vec![
            name.clone(),
            cpus.to_string(),
            mem.to_string(),
            disk.to_string(),
            v["os"].as_str().unwrap_or("").to_string(),
            v["shapes"]
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect::<Vec<_>>()
                .join(", "),
        ]);
    }
    rows.push(vec!["total".into(), c.to_string(), m.to_string(), d.to_string(), String::new(), String::new()]);
    (head, rows)
}

/// Aligned text columns, or a Markdown table.
pub fn table(head: &[String], rows: &[Vec<String>], markdown: bool) -> String {
    let mut out = String::new();
    if markdown {
        let _ = writeln!(out, "| {} |", head.join(" | "));
        let _ = writeln!(out, "|{}", " --- |".repeat(head.len()));
        for r in rows {
            let _ = writeln!(out, "| {} |", r.iter().map(|c| c.replace('|', "\\|")).collect::<Vec<_>>().join(" | "));
        }
        return out;
    }
    let widths: Vec<usize> = (0..head.len())
        .map(|i| {
            rows.iter()
                .map(|r| r.get(i).map(String::len).unwrap_or(0))
                .chain(std::iter::once(head[i].len()))
                .max()
                .unwrap_or(0)
        })
        .collect();
    let line = |cells: &[String]| -> String {
        cells
            .iter()
            .enumerate()
            .map(|(i, c)| format!("{:<w$}", c, w = widths[i]))
            .collect::<Vec<_>>()
            .join("  ")
            .trim_end()
            .to_string()
    };
    let _ = writeln!(out, "{}", line(head));
    for r in rows {
        let _ = writeln!(out, "{}", line(r));
    }
    out
}
