#!/bin/sh
# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Creates the services (`isoloom run cloud-services`).
# The services of `cloud-bucket`: the Terraform module `terraform`, in the user's aws account.
set -eu
cd "$(dirname "$0")"
here="$(pwd)"
export TF_DATA_DIR="$here/.terraform"
module='../../terraform'
terraform -chdir="$module" init -input=false >&2
terraform -chdir="$module" apply -auto-approve -input=false -state="$here/terraform.tfstate" -var-file="$here/terraform.tfvars.json"
