#!/bin/sh
# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# The environment's checks, from cache. `isoloom test` runs it and reads the PASS/FAIL lines.
passed=0; failed=0
pass() { passed=$((passed+1)); echo "isoloom-check: PASS $1"; }
fail() { failed=$((failed+1)); echo "isoloom-check: FAIL $1: $2"; }
# _http URL -> the status code, 000 when nothing answers (curl, else wget, else bash).
_http() {
  if command -v curl >/dev/null 2>&1; then
    c=$(curl -sk -o /dev/null -m 5 -w '%{http_code}' "$1" 2>/dev/null)
  elif command -v wget >/dev/null 2>&1; then
    c=$(wget -q -S -O /dev/null -T 5 --no-check-certificate "$1" 2>&1 | sed -n 's/^ *HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p' | tail -n 1)
  else
    u=${1#*://}; hp=${u%%/*}; p=/${u#*/}; [ "$u" = "$hp" ] && p=/
    h=${hp%%:*}; port=${hp#*:}; [ "$hp" = "$h" ] && port=80
    c=$(H=$h P=$port U=$p timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P && printf "GET %s HTTP/1.0\r\nHost: %s\r\n\r\n" "$U" "$H" >&3 && read -r l <&3 && echo "$l"' 2>/dev/null | sed -n 's/^HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p')
  fi
  echo "${c:-000}"
}
_http_is() { [ "$(_http "$1")" = "$2" ]; }
_http_any() { [ "$(_http "$1")" != 000 ]; }
# _tcp HOST PORT -> 0 when it connects (nc, else bash).
_tcp() {
  if command -v nc >/dev/null 2>&1; then nc -z -w 5 "$1" "$2" >/dev/null 2>&1
  else H=$1 P=$2 timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P' >/dev/null 2>&1
  fi
}
# _exec COMMAND TEXT -> 0 when the command succeeds and its output contains TEXT (if any).
_exec() { out=$(sh -c "$1" 2>&1) && { [ -z "$2" ] || printf '%s\n' "$out" | grep -qF -- "$2"; }; }
# _retry SECONDS COMMAND... -> keeps trying every 2s until it passes or the time is up.
_retry() { _end=$(( $(date +%s) + $1 )); shift; while ! "$@"; do [ "$(date +%s)" -lt "$_end" ] || return 1; sleep 2; done; }

if [ "${ISOLOOM_DERIVED:-1}" != 0 ]; then
if _tcp '10.61.10.10' 80; then fail 'web:80 blocked from cache' "10.61.10.10:80 answered; it should be blocked"; else pass 'web:80 blocked from cache'; fi
fi

if [ "${ISOLOOM_DERIVED:-1}" != 0 ]; then
c=$(_http 'http://1.1.1.1/'); if [ "$c" = 000 ]; then pass 'no internet from cache'; else fail 'no internet from cache' "http://1.1.1.1/ answered (HTTP $c); it should be blocked"; fi
fi

echo "isoloom-check: END $passed passed, $failed failed"
[ "$failed" -eq 0 ]
