# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/cloud-docker/oci init && terraform -chdir=.isoloom/cloud-docker/oci apply \
#           -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-docker/oci destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 9.0"
    }
  }
}

variable "compartment_id" {
  type = string
}
variable "region" {
  type    = string
  default = "eu-paris-1"
}

provider "oci" {
  region = var.region
}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-supplier-portal-api-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
}

data "oci_identity_availability_domains" "ads" {
  compartment_id = var.compartment_id
}

# Ubuntu: Oracle Cloud has no Debian image of its own.
data "oci_core_images" "ubuntu" {
  compartment_id           = var.compartment_id
  operating_system         = "Canonical Ubuntu"
  operating_system_version = "24.04"
  shape                    = "VM.Standard.E4.Flex"
  sort_by                  = "TIMECREATED"
  sort_order               = "DESC"
}

resource "oci_core_vcn" "env" {
  compartment_id = var.compartment_id
  display_name   = local.name
  cidr_blocks    = ["10.42.0.0/16"]
}

resource "oci_core_internet_gateway" "env" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.env.id
  display_name   = local.name
}

resource "oci_core_route_table" "env" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.env.id
  route_rules {
    destination       = "0.0.0.0/0"
    network_entity_id = oci_core_internet_gateway.env.id
  }
}

resource "oci_core_security_list" "env" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.env.id
  display_name   = local.name
  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "all"
  }
  dynamic "ingress_security_rules" {
    for_each = concat([22], [3206])
    content {
      source   = var.allowed_cidr
      protocol = "6"
      tcp_options {
        min = ingress_security_rules.value
        max = ingress_security_rules.value
      }
    }
  }
}

resource "oci_core_subnet" "env" {
  compartment_id    = var.compartment_id
  vcn_id            = oci_core_vcn.env.id
  cidr_block        = "10.42.1.0/24"
  display_name      = local.name
  route_table_id    = oci_core_route_table.env.id
  security_list_ids = [oci_core_security_list.env.id]
}

resource "oci_core_instance" "env" {
  compartment_id      = var.compartment_id
  availability_domain = data.oci_identity_availability_domains.ads.availability_domains[0].name
  display_name        = local.name
  shape               = "VM.Standard.E4.Flex"
  shape_config {
    ocpus         = 1
    memory_in_gbs = 4
  }
  source_details {
    source_type = "image"
    source_id   = data.oci_core_images.ubuntu.images[0].id
  }
  create_vnic_details {
    subnet_id        = oci_core_subnet.env.id
    assign_public_ip = true
  }
  metadata = {
    ssh_authorized_keys = var.ssh_public_key
  }
}

variable "allowed_cidr" {
  type        = string
  description = "Who may reach the VM (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform copies the project over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the VM down after this many minutes (0: never). Destroy still ends the billing of disks and addresses"
}
variable "inputs" {
  type      = map(string)
  default   = {}
  sensitive = true
}

# The environment, over SSH: the project, Docker, then the Compose file.
resource "terraform_data" "environment" {
  triggers_replace = [oci_core_instance.env.id]
  connection {
    type        = "ssh"
    host        = oci_core_instance.env.public_ip
    user        = "ubuntu"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = [
      "cloud-init status --wait >/dev/null 2>&1 || true",
      var.auto_stop_minutes > 0 ? "sudo shutdown -h +${var.auto_stop_minutes} >/dev/null 2>&1" : "true",
      "sudo mkdir -p /opt/isoloom && sudo chown ubuntu /opt/isoloom",
    ]
  }
  # The project as an archive: a plain copy drops the executable bits (entrypoint scripts).
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "file" {
    content     = join("\n", [for k, v in var.inputs : "${k}=${jsonencode(v)}"])
    destination = "/tmp/isoloom-inputs.env"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "command -v docker >/dev/null || curl -fsSL https://get.docker.com | sudo sh",
      "cd /opt/isoloom && set -a; . /tmp/isoloom-inputs.env; set +a; sudo -E env ISOLOOM_PUBLISH_ADDRESS=0.0.0.0 ISOLOOM_PUBLISH_FIXED=1 docker compose -f .isoloom/docker/compose.yml up -d --build --wait --wait-timeout 900",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null",
    ]
  }
}

output "ip" {
  value = oci_core_instance.env.public_ip
}
output "ssh_user" {
  value = "ubuntu"
}
output "ready_file" {
  value = "/var/lib/isoloom/ready"
}
