# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Auth:   export LINODE_TOKEN=<token> (the provider reads it).
# Start:  terraform -chdir=.isoloom/cloud-vm/linode init && terraform -chdir=.isoloom/cloud-vm/linode apply \
#           -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/linode destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

variable "region" {
  type    = string
  default = "fr-par"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machines (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machines up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machines down after this many minutes (0: never)"
}

provider "linode" {}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-existing-hosts-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
}

# The environment's one network: a VPC with a subnet at its exact range, so every machine keeps
# its address (192.168.1.0/24).
resource "linode_vpc" "env" {
  label  = local.name
  region = var.region
}

resource "linode_vpc_subnet" "env" {
  vpc_id = linode_vpc.env.id
  label  = "lab"
  ipv4   = "192.168.1.0/24"
}

resource "linode_firewall" "env" {
  label           = local.name
  inbound_policy  = "DROP"
  outbound_policy = "ACCEPT"
  inbound {
    label    = "ssh"
    action   = "ACCEPT"
    protocol = "TCP"
    ports    = "22"
    ipv4     = [var.allowed_cidr]
  }
  inbound {
    label    = "vpc-tcp"
    action   = "ACCEPT"
    protocol = "TCP"
    ports    = "1-65535"
    ipv4     = ["192.168.1.0/24"]
  }
  inbound {
    label    = "vpc-udp"
    action   = "ACCEPT"
    protocol = "UDP"
    ports    = "1-65535"
    ipv4     = ["192.168.1.0/24"]
  }
  inbound {
    label    = "vpc-icmp"
    action   = "ACCEPT"
    protocol = "ICMP"
    ipv4     = ["192.168.1.0/24"]
  }
  linodes = [linode_instance.web.id, linode_instance.cache.id]
}

resource "random_password" "web" {
  length      = 24
  special     = false
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
}

resource "linode_instance" "web" {
  label           = "${local.name}-web"
  region          = var.region
  type            = "g6-nanode-1"
  image           = "linode/debian12"
  authorized_keys = [trimspace(var.ssh_public_key)]
  root_pass       = random_password.web.result
  booted          = true
  tags            = ["isoloom", "existing-hosts"]
  metadata {
    user_data = base64encode(var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : "")
  }
  interface {
    purpose = "public"
  }
  interface {
    purpose   = "vpc"
    subnet_id = linode_vpc_subnet.env.id
    ipv4 {
      vpc = "192.168.1.20"
    }
  }
}

resource "terraform_data" "web" {
  triggers_replace = [linode_instance.web.id]
  connection {
    type        = "ssh"
    host        = one(linode_instance.web.ipv4)
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "command -v sudo >/dev/null || (apt-get update -qq && apt-get install -y -qq sudo)", "sudo mkdir -p /opt/isoloom && sudo chown root /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-web.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project* -X \"${abspath(local_file.isoloom_project.filename)}\" -C \"${dirname(local.root)}\" \"${basename(local.root)}\""
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-web.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom --strip-components=1 && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '192.168.1.21 cache' | sudo tee -a /etc/hosts >/dev/null",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/web.sh'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [linode_firewall.env]
}

resource "random_password" "cache" {
  length      = 24
  special     = false
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
}

resource "linode_instance" "cache" {
  label           = "${local.name}-cache"
  region          = var.region
  type            = "g6-nanode-1"
  image           = "linode/debian12"
  authorized_keys = [trimspace(var.ssh_public_key)]
  root_pass       = random_password.cache.result
  booted          = true
  tags            = ["isoloom", "existing-hosts"]
  metadata {
    user_data = base64encode(var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : "")
  }
  interface {
    purpose = "public"
  }
  interface {
    purpose   = "vpc"
    subnet_id = linode_vpc_subnet.env.id
    ipv4 {
      vpc = "192.168.1.21"
    }
  }
}

resource "terraform_data" "cache" {
  triggers_replace = [linode_instance.cache.id]
  connection {
    type        = "ssh"
    host        = one(linode_instance.cache.ipv4)
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "command -v sudo >/dev/null || (apt-get update -qq && apt-get install -y -qq sudo)", "sudo mkdir -p /opt/isoloom && sudo chown root /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-cache.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project* -X \"${abspath(local_file.isoloom_project.filename)}\" -C \"${dirname(local.root)}\" \"${basename(local.root)}\""
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-cache.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom --strip-components=1 && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '192.168.1.20 web' | sudo tee -a /etc/hosts >/dev/null",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/cache.sh'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [linode_firewall.env]
}

output "machines" {
  value = {
    web   = one(linode_instance.web.ipv4)
    cache = one(linode_instance.cache.ipv4)
  }
}

output "ssh_users" {
  value = {
    web   = "root"
    cache = "root"
  }
}

output "ip" {
  value = one(linode_instance.web.ipv4)
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}

# The checks: each runner on the machine it stands for (ssh <user>@<host> '<command>'), or `isoloom test cloud-vm`.
output "checks" {
  value = [
    { position = "web", machine = "web", host = one(linode_instance.web.ipv4), user = "root", command = "cd /opt/isoloom && sh .isoloom/cloud-vm/checks/web.sh" },
    { position = "cache", machine = "cache", host = one(linode_instance.cache.ipv4), user = "root", command = "cd /opt/isoloom && sh .isoloom/cloud-vm/checks/cache.sh" }
  ]
}

# The project's files the machines don't get: version control and the tools' state, and what
# .isoloomignore at the project's root lists (gitignore-style: one pattern per line, `#` comments,
# `!` brings a path back, a trailing `/` matches folders only, a `/` at the start or in the middle
# anchors the pattern at the root; `*`, `?`, `[abc]`, `**`; the last pattern matching a path, or
# a folder it is in, decides). Read as regular expressions, as the Vagrantfiles do.
locals {
  project_ignore_lines = [for l in split("\n", replace(try(file("${local.root}/.isoloomignore"), ""), "\r", "")) : trimspace(l)]
  project_ignore_pats  = [for l in local.project_ignore_lines : { keep = startswith(l, "!"), pat = trimprefix(l, "!") } if l != "" && !startswith(l, "#")]
  project_ignore_globs = [for r in local.project_ignore_pats : merge(r, { glob = trimsuffix(trimsuffix(trimsuffix(r.pat, "/"), "/**"), "/") })]
  project_ignore = [for r in local.project_ignore_globs : {
    keep = r.keep
    re = format(r.glob == r.pat ? "^%s(/|$)" : "^%s/", replace(replace(replace(replace(replace(replace(replace(replace(
      length(split("/", r.glob)) > 1 ? trimprefix(r.glob, "/") : "**/${r.glob}",
    "/[.+^$(){}|\\\\]/", "\\$0"), "[!", "[^"), "**/", "\u0001"), "**", "\u0002"), "*", "[^/]*"), "?", "[^/]"), "\u0001", "(.*/)?"), "\u0002", ".*"))
  } if r.glob != ""]
  # Each file: whether it goes (the last matching pattern decides; none: it goes).
  project_keep    = { for f in fileset(local.root, "**") : f => reverse(concat([true], [for r in local.project_ignore : r.keep if length(regexall(r.re, f)) > 0]))[0] }
  project_paths   = [for f, keep in local.project_keep : f if keep && length(regexall("^\\.isoloom|(^|/)\\.(git|vagrant|terraform)/", f)) == 0]
  project_ignored = [for f, keep in local.project_keep : f if !keep]
}

# What `tar` leaves out of the project's archive: .isoloomignore's files, from the archive's top
# folder, their wildcard characters escaped.
resource "local_file" "isoloom_project" {
  filename = "${path.module}/.isoloom-project-ignored.txt"
  content  = join("", [for f in local.project_ignored : "${replace("${basename(local.root)}/${f}", "/[\\\\*?\\[]/", "\\$0")}\n"])
}
