# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/cloud-docker/gcp init && terraform -chdir=.isoloom/cloud-docker/gcp apply \
#           -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-docker/gcp destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 8.0"
    }
  }
}

variable "project" {
  type        = string
  default     = ""
  description = "An existing project; or leave empty and give billing_account for a project of its own"
}
variable "billing_account" {
  type        = string
  default     = ""
  description = "With no project: create one for this environment, billed here, deleted with it"
}
variable "org_id" {
  type    = string
  default = ""
}
variable "region" {
  type    = string
  default = "europe-west9"
}
variable "machine_type" {
  type    = string
  default = "e2-medium"
}

provider "google" {
  region = var.region
}

# A project of its own when none is given: everything goes when the environment is destroyed.
resource "google_project" "env" {
  count               = var.project == "" ? 1 : 0
  name                = "isoloom-segmented"
  project_id          = "isoloom-${terraform_data.id.output}"
  billing_account     = var.billing_account
  org_id              = var.org_id == "" ? null : var.org_id
  deletion_policy     = "DELETE"
  auto_create_network = false
}

resource "google_project_service" "compute" {
  count              = var.project == "" ? 1 : 0
  project            = google_project.env[0].project_id
  service            = "compute.googleapis.com"
  disable_on_destroy = false
}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name    = "isoloom-segmented-${terraform_data.id.output}"
  root    = abspath("${path.module}/../../..")
  project = var.project != "" ? var.project : google_project_service.compute[0].project
}

resource "google_compute_network" "env" {
  project                 = local.project
  name                    = local.name
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "env" {
  project       = local.project
  name          = local.name
  network       = google_compute_network.env.id
  ip_cidr_range = "10.42.1.0/24"
  region        = var.region
}

resource "google_compute_firewall" "env" {
  project       = local.project
  name          = local.name
  network       = google_compute_network.env.id
  source_ranges = [var.allowed_cidr]
  allow {
    protocol = "tcp"
    ports    = concat(["22"], [])
  }
}

resource "google_compute_instance" "env" {
  project      = local.project
  name         = local.name
  machine_type = var.machine_type
  zone         = "${var.region}-a"
  labels       = { "isoloom-environment" = "segmented", "managed-by" = "isoloom", "isoloom-instance" = local.name, "isoloom-expires-at" = var.expires_at }
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 30
    }
  }
  network_interface {
    subnetwork = google_compute_subnetwork.env.id
    access_config {}
  }
  metadata = {
    ssh-keys = "isoloom:${var.ssh_public_key}"
  }
}

variable "allowed_cidr" {
  type        = string
  description = "Who may reach the VM (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform copies the project over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the VM down after this many minutes (0: never). Destroy still ends the billing of disks and addresses"
}

variable "expires_at" {
  type        = string
  default     = ""
  description = "When the environment should end, in Unix seconds (empty: no end), as a tag on every resource so a reaper can find what to destroy"
}

# The environment, over SSH: the project, Docker, then the Compose file.
resource "terraform_data" "environment" {
  triggers_replace = [google_compute_instance.env.id]
  connection {
    type        = "ssh"
    host        = google_compute_instance.env.network_interface[0].access_config[0].nat_ip
    user        = "isoloom"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = [
      "cloud-init status --wait >/dev/null 2>&1 || true",
      var.auto_stop_minutes > 0 ? "sudo shutdown -h +${var.auto_stop_minutes} >/dev/null 2>&1" : "true",
      "sudo mkdir -p /opt/isoloom && sudo chown isoloom /opt/isoloom",
    ]
  }
  # The project as an archive: a plain copy drops the executable bits (entrypoint scripts).
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "command -v docker >/dev/null || curl -fsSL https://get.docker.com | sudo sh",
      "cd /opt/isoloom && sudo -E env ISOLOOM_PUBLISH_ADDRESS=0.0.0.0 ISOLOOM_PUBLISH_FIXED=1 docker compose -f .isoloom/docker/compose.yml up -d --build --wait --wait-timeout 900",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null",
    ]
  }
}

output "ip" {
  value = google_compute_instance.env.network_interface[0].access_config[0].nat_ip
}
output "ssh_user" {
  value = "isoloom"
}
output "ready_file" {
  value = "/var/lib/isoloom/ready"
}
