# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/cloud-vm/gcp init && terraform -chdir=.isoloom/cloud-vm/gcp apply \
#           -var project=<id> -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/gcp destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
}

variable "project" {
  type        = string
  description = "The Google Cloud project to build in"
}
variable "region" {
  type    = string
  default = "europe-west1"
}
variable "zone" {
  type    = string
  default = "europe-west1-b"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machines (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machines up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machines down after this many minutes (0: never)"
}
variable "inputs" {
  type        = map(string)
  default     = {}
  sensitive   = true
  description = "Values given at launch"
}

provider "google" {
  project = var.project
  region  = var.region
  zone    = var.zone
}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-supplier-portal-api-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
}

# The environment's networks: one VPC, a subnetwork per network with its exact range.
resource "google_compute_network" "env" {
  name                    = local.name
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "lab" {
  name          = "${local.name}-lab"
  network       = google_compute_network.env.id
  ip_cidr_range = "10.20.0.0/24"
  region        = var.region
}

# Machine `database`: what may reach it.
resource "google_compute_firewall" "database_net" {
  name          = "${local.name}-database-net"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = ["10.20.0.0/24"]
  target_tags   = ["${local.name}-database"]
  allow {
    protocol = "all"
  }
}

resource "google_compute_firewall" "database_ssh" {
  name          = "${local.name}-database-ssh"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = [var.allowed_cidr]
  target_tags   = ["${local.name}-database"]
  allow {
    protocol = "tcp"
    ports    = ["22"]
  }
}

resource "google_compute_instance" "database" {
  name         = "${local.name}-database"
  machine_type = "e2-small"
  zone         = var.zone
  tags         = ["${local.name}-database"]
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 20
    }
  }
  network_interface {
    subnetwork = google_compute_subnetwork.lab.id
    network_ip = "10.20.0.32"
    access_config {}
  }
  metadata = {
    ssh-keys = "admin:${var.ssh_public_key}"
  }
  metadata_startup_script = var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : null
  labels = {
    "isoloom-environment" = "supplier-portal-api"
    "managed-by"          = "isoloom"
  }
}

resource "terraform_data" "database" {
  triggers_replace = [google_compute_instance.database.id]
  connection {
    type        = "ssh"
    host        = google_compute_instance.database.network_interface[0].access_config[0].nat_ip
    user        = "admin"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown admin /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-database.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-database.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "file" {
    content     = join("\n", ["API_URL=${jsonencode(lookup(var.inputs, "API_URL", ""))}", "LAUNCH_TOKEN=${jsonencode(lookup(var.inputs, "LAUNCH_TOKEN", ""))}"])
    destination = "/tmp/isoloom-inputs.env"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '10.20.0.31 web' | sudo tee -a /etc/hosts >/dev/null",
      "cd /opt/isoloom && sudo -E sh -c 'set -a; . /tmp/isoloom-inputs.env; set +a; sh provision/database.sh'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
}

# Machine `web`: what may reach it.
resource "google_compute_firewall" "web_net" {
  name          = "${local.name}-web-net"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = ["10.20.0.0/24"]
  target_tags   = ["${local.name}-web"]
  allow {
    protocol = "all"
  }
}

resource "google_compute_firewall" "web_ssh" {
  name          = "${local.name}-web-ssh"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = [var.allowed_cidr]
  target_tags   = ["${local.name}-web"]
  allow {
    protocol = "tcp"
    ports    = ["22"]
  }
}

resource "google_compute_firewall" "web_published" {
  name          = "${local.name}-web-published"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = [var.allowed_cidr]
  target_tags   = ["${local.name}-web"]
  allow {
    protocol = "tcp"
    ports    = ["3206"]
  }
}

resource "google_compute_instance" "web" {
  name         = "${local.name}-web"
  machine_type = "e2-small"
  zone         = var.zone
  tags         = ["${local.name}-web"]
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 20
    }
  }
  network_interface {
    subnetwork = google_compute_subnetwork.lab.id
    network_ip = "10.20.0.31"
    access_config {}
  }
  metadata = {
    ssh-keys = "admin:${var.ssh_public_key}"
  }
  metadata_startup_script = var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : null
  labels = {
    "isoloom-environment" = "supplier-portal-api"
    "managed-by"          = "isoloom"
  }
}

resource "terraform_data" "web" {
  triggers_replace = [google_compute_instance.web.id]
  connection {
    type        = "ssh"
    host        = google_compute_instance.web.network_interface[0].access_config[0].nat_ip
    user        = "admin"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown admin /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-web.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-web.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '10.20.0.32 database' | sudo tee -a /etc/hosts >/dev/null",
      "sh -c 'i=0; until (bash -c '\\''</dev/tcp/database/3207'\\'' 2>/dev/null || nc -z -w 2 database 3207 2>/dev/null); do i=$((i+2)); if [ $i -ge 900 ]; then echo \"database didn'\\''t answer within 900s\" >&2; exit 1; fi; sleep 2; done; echo \"database answers\"'",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/web.sh'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [terraform_data.database]
}

output "machines" {
  value = {
    database = google_compute_instance.database.network_interface[0].access_config[0].nat_ip
    web      = google_compute_instance.web.network_interface[0].access_config[0].nat_ip
  }
}

output "ssh_users" {
  value = {
    database = "admin"
    web      = "admin"
  }
}

output "ip" {
  value = google_compute_instance.database.network_interface[0].access_config[0].nat_ip
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}

# The checks, from where a user stands: ssh <user>@<host> each command.
output "checks" {
  value = {
    host = google_compute_instance.database.network_interface[0].access_config[0].nat_ip
    user = null
    commands = [
      "cd /opt/isoloom && sh build/check/check.sh"
    ]
  }
}

output "published" {
  value = {
    "web/portal" = "${google_compute_instance.web.network_interface[0].access_config[0].nat_ip}:3206"
  }
}
