# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/cloud-docker/azure init && terraform -chdir=.isoloom/cloud-docker/azure apply \
#           -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-docker/azure destroy (same variables)

terraform {
  required_version = ">= 1.6"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 5.0"
    }
  }
}

variable "subscription_id" {
  type = string
}
variable "location" {
  type    = string
  default = "francecentral"
}
variable "size" {
  type    = string
  default = "Standard_B2s"
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-segmented-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
  tags = { "isoloom-environment" = "segmented", "managed-by" = "isoloom" }
}

resource "azurerm_resource_group" "env" {
  name     = local.name
  location = var.location
  tags     = local.tags
}

resource "azurerm_virtual_network" "env" {
  name                = local.name
  resource_group_name = azurerm_resource_group.env.name
  location            = var.location
  address_space       = ["10.42.0.0/16"]
}

resource "azurerm_subnet" "env" {
  name                 = local.name
  resource_group_name  = azurerm_resource_group.env.name
  virtual_network_name = azurerm_virtual_network.env.name
  address_prefixes     = ["10.42.1.0/24"]
}

resource "azurerm_public_ip" "env" {
  name                = local.name
  resource_group_name = azurerm_resource_group.env.name
  location            = var.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_network_security_group" "env" {
  name                = local.name
  resource_group_name = azurerm_resource_group.env.name
  location            = var.location
  security_rule {
    name                       = "ssh-and-published"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_ranges    = concat(["22"], [])
    source_address_prefix      = var.allowed_cidr
    destination_address_prefix = "*"
  }
}

resource "azurerm_network_interface" "env" {
  name                = local.name
  resource_group_name = azurerm_resource_group.env.name
  location            = var.location
  ip_configuration {
    name                          = "env"
    subnet_id                     = azurerm_subnet.env.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.env.id
  }
}

resource "azurerm_network_interface_security_group_association" "env" {
  network_interface_id      = azurerm_network_interface.env.id
  network_security_group_id = azurerm_network_security_group.env.id
}

resource "azurerm_linux_virtual_machine" "env" {
  name                  = local.name
  resource_group_name   = azurerm_resource_group.env.name
  location              = var.location
  size                  = var.size
  admin_username        = "isoloom"
  network_interface_ids = [azurerm_network_interface.env.id]
  admin_ssh_key {
    username   = "isoloom"
    public_key = var.ssh_public_key
  }
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }
  source_image_reference {
    publisher = "Debian"
    offer     = "debian-12"
    sku       = "12-gen2"
    version   = "latest"
  }
  tags       = local.tags
  depends_on = [azurerm_network_interface_security_group_association.env]
}

variable "allowed_cidr" {
  type        = string
  description = "Who may reach the VM (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform copies the project over SSH"
}

# The environment, over SSH: the project, Docker, then the Compose file.
resource "terraform_data" "environment" {
  triggers_replace = [azurerm_linux_virtual_machine.env.id]
  connection {
    type        = "ssh"
    host        = azurerm_public_ip.env.ip_address
    user        = "isoloom"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown isoloom /opt/isoloom"]
  }
  provisioner "file" {
    source      = "${local.root}/"
    destination = "/opt/isoloom"
  }
  provisioner "remote-exec" {
    inline = [
      "command -v docker >/dev/null || curl -fsSL https://get.docker.com | sudo sh",
      "cd /opt/isoloom && sudo -E env ISOLOOM_PUBLISH_ADDRESS=0.0.0.0 docker compose -f .isoloom/docker/compose.yml up -d --build --wait --wait-timeout 900",
      "sudo mkdir -p /var/lib/isoloom && sudo touch /var/lib/isoloom/ready",
    ]
  }
}

output "ip" {
  value = azurerm_public_ip.env.ip_address
}
output "ssh_user" {
  value = "isoloom"
}
output "ready_file" {
  value = "/var/lib/isoloom/ready"
}
