# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/cloud-vm/oci init && terraform -chdir=.isoloom/cloud-vm/oci apply \
#           -var compartment_id=<compartment ocid> -var allowed_cidr=<your IP>/32 \
#           -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/oci destroy (same variables)
# Auth:   the oci provider reads ~/.oci/config; region defaults, override with -var region=<id>.

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 6.0"
    }
  }
}

variable "compartment_id" {
  type        = string
  description = "The compartment the environment goes in"
}
variable "region" {
  type        = string
  default     = "eu-paris-1"
  description = "The OCI region to launch in"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machines (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machines up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machines down after this many minutes (0: never)"
}
variable "inputs" {
  type        = map(string)
  default     = {}
  sensitive   = true
  description = "Values given at launch"
}

provider "oci" {
  region = var.region
}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-supplier-portal-api-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
}

# The compartment's availability domains; the instances land in the first.
data "oci_identity_availability_domains" "ads" {
  compartment_id = var.compartment_id
}

# Ubuntu 24.04: Oracle Cloud has no Debian image of its own.
data "oci_core_images" "ubuntu_2404" {
  compartment_id           = var.compartment_id
  operating_system         = "Canonical Ubuntu"
  operating_system_version = "24.04"
  shape                    = "VM.Standard.E4.Flex"
  sort_by                  = "TIMECREATED"
  sort_order               = "DESC"
}

# The environment's one network: a VCN with the spec's range, routed to the internet.
resource "oci_core_vcn" "env" {
  compartment_id = var.compartment_id
  cidr_block     = "10.20.0.0/24"
  display_name   = local.name
}

resource "oci_core_internet_gateway" "env" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.env.id
  display_name   = local.name
}

resource "oci_core_route_table" "env" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.env.id
  display_name   = local.name
  route_rules {
    destination       = "0.0.0.0/0"
    network_entity_id = oci_core_internet_gateway.env.id
  }
}

# What may reach the machines: everything inside the VCN, SSH and the published ports from
# allowed_cidr; egress open.
resource "oci_core_security_list" "env" {
  compartment_id = var.compartment_id
  vcn_id         = oci_core_vcn.env.id
  display_name   = local.name
  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "all"
  }
  ingress_security_rules {
    description = "the VCN itself"
    source      = "10.20.0.0/24"
    protocol    = "all"
  }
  ingress_security_rules {
    description = "SSH from allowed_cidr"
    source      = var.allowed_cidr
    protocol    = "6"
    tcp_options {
      min = 22
      max = 22
    }
  }
  ingress_security_rules {
    description = "published"
    source      = var.allowed_cidr
    protocol    = "6"
    tcp_options {
      min = 3206
      max = 3206
    }
  }
}

resource "oci_core_subnet" "env" {
  compartment_id    = var.compartment_id
  vcn_id            = oci_core_vcn.env.id
  cidr_block        = "10.20.0.0/24"
  display_name      = local.name
  route_table_id    = oci_core_route_table.env.id
  security_list_ids = [oci_core_security_list.env.id]
}

# Machine `database`, at its fixed address 10.20.0.32.
resource "oci_core_instance" "database" {
  compartment_id      = var.compartment_id
  availability_domain = data.oci_identity_availability_domains.ads.availability_domains[0].name
  display_name        = "${local.name}-database"
  shape               = "VM.Standard.E4.Flex"
  shape_config {
    ocpus         = 1
    memory_in_gbs = 1
  }
  source_details {
    source_type             = "image"
    source_id               = data.oci_core_images.ubuntu_2404.images[0].id
    boot_volume_size_in_gbs = 50
  }
  create_vnic_details {
    subnet_id        = oci_core_subnet.env.id
    private_ip       = "10.20.0.32"
    assign_public_ip = true
    hostname_label   = "database"
  }
  metadata = {
    ssh_authorized_keys = var.ssh_public_key
    user_data           = base64encode(var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : "#!/bin/sh\n")
  }
}

resource "terraform_data" "database" {
  triggers_replace = [oci_core_instance.database.id]
  connection {
    type        = "ssh"
    host        = oci_core_instance.database.public_ip
    user        = "ubuntu"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown ubuntu /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-database.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-database.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "file" {
    content     = join("\n", ["API_URL=${jsonencode(lookup(var.inputs, "API_URL", ""))}", "LAUNCH_TOKEN=${jsonencode(lookup(var.inputs, "LAUNCH_TOKEN", ""))}"])
    destination = "/tmp/isoloom-inputs.env"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '10.20.0.31 web' | sudo tee -a /etc/hosts >/dev/null",
      "cd /opt/isoloom && sudo -E sh -c 'set -a; . /tmp/isoloom-inputs.env; set +a; sh provision/database.sh'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
}

# Machine `web`, at its fixed address 10.20.0.31.
resource "oci_core_instance" "web" {
  compartment_id      = var.compartment_id
  availability_domain = data.oci_identity_availability_domains.ads.availability_domains[0].name
  display_name        = "${local.name}-web"
  shape               = "VM.Standard.E4.Flex"
  shape_config {
    ocpus         = 1
    memory_in_gbs = 1
  }
  source_details {
    source_type             = "image"
    source_id               = data.oci_core_images.ubuntu_2404.images[0].id
    boot_volume_size_in_gbs = 50
  }
  create_vnic_details {
    subnet_id        = oci_core_subnet.env.id
    private_ip       = "10.20.0.31"
    assign_public_ip = true
    hostname_label   = "web"
  }
  metadata = {
    ssh_authorized_keys = var.ssh_public_key
    user_data           = base64encode(var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : "#!/bin/sh\n")
  }
}

resource "terraform_data" "web" {
  triggers_replace = [oci_core_instance.web.id]
  connection {
    type        = "ssh"
    host        = oci_core_instance.web.public_ip
    user        = "ubuntu"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown ubuntu /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-web.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-web.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '10.20.0.32 database' | sudo tee -a /etc/hosts >/dev/null",
      "sh -c 'i=0; until (bash -c '\\''</dev/tcp/database/3207'\\'' 2>/dev/null || nc -z -w 2 database 3207 2>/dev/null); do i=$((i+2)); if [ $i -ge 900 ]; then echo \"database didn'\\''t answer within 900s\" >&2; exit 1; fi; sleep 2; done; echo \"database answers\"'",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/web.sh'",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [terraform_data.database]
}

output "machines" {
  value = {
    database = oci_core_instance.database.public_ip
    web      = oci_core_instance.web.public_ip
  }
}

output "ssh_users" {
  value = {
    database = "ubuntu"
    web      = "ubuntu"
  }
}

output "ip" {
  value = oci_core_instance.database.public_ip
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}

# The checks, from where a user stands: ssh <user>@<host> each command.
output "checks" {
  value = {
    host = oci_core_instance.database.public_ip
    user = null
    commands = [
      "cd /opt/isoloom && sh build/check/check.sh"
    ]
  }
}

output "published" {
  value = {
    "web/portal" = "${oci_core_instance.web.public_ip}:3206"
  }
}
