//! Generators against the examples: the committed files under each example's `.isoloom/`
//! are exactly what `generate` produces (what `isoloom check` enforces in CI), and specs
//! a generator can't handle yet are refused with the reason.

use std::path::{Path, PathBuf};

use isoloom_core::{GenerateError, Target, generate, generate_all, load};

fn example(name: &str) -> (PathBuf, isoloom_core::Spec) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples").join(name);
    let spec = load(&dir).expect("example parses");
    (dir, spec)
}

fn assert_committed(name: &str) {
    let (dir, spec) = example(name);
    let (files, _) = generate_all(&spec);
    assert!(!files.is_empty(), "{name}: nothing generated");
    for f in files {
        let on_disk = std::fs::read_to_string(dir.join(&f.path)).unwrap_or_default();
        assert!(
            on_disk == f.contents,
            "{name}: {} is stale; run `cargo run -- generate examples/{name}`",
            f.path
        );
    }
}

#[test]
fn committed_outputs_are_up_to_date() {
    assert_committed("hello-stack");
    assert_committed("supplier-portal-api");
    assert_committed("segmented");
    assert_committed("pivot-dmz");
    assert_committed("edge-firewall");
    assert_committed("air-gapped");
    assert_committed("windows-hello");
    assert_committed("ansible-pair");
}

#[test]
fn compose_has_addresses_healthchecks_init_and_checks() {
    let (_, spec) = example("hello-stack");
    let compose = &generate(&spec, Target::Docker).unwrap()[0].contents;
    assert!(compose.contains("ipv4_address: 10.60.0.20"));
    assert!(compose.contains("gateway: 10.60.0.1"));
    assert!(compose.contains("nc -z 127.0.0.1 6379"));
    assert!(compose.contains("cache-init-1:"));
    assert!(compose.contains("condition: service_completed_successfully"));
    assert!(compose.contains("isoloom-check:"));
    assert!(compose.starts_with("# Generated by isoloom"));
}

#[test]
fn inputs_reach_only_the_machines_that_list_them() {
    let (_, spec) = example("supplier-portal-api");
    let compose = &generate(&spec, Target::Docker).unwrap()[0].contents;
    let web = compose.split("\n  web:").nth(1).unwrap().split("\n  isoloom-check:").next().unwrap();
    assert!(compose.contains("LAUNCH_TOKEN: ${LAUNCH_TOKEN:-}"));
    assert!(!web.contains("LAUNCH_TOKEN"), "web must not receive the database's inputs");
}

#[test]
fn vagrant_orders_machines_and_names_them() {
    let (_, spec) = example("hello-stack");
    let vf = &generate(&spec, Target::Vagrant).unwrap()[0].contents;
    let cache = vf.find("config.vm.define \"cache\"").unwrap();
    let web = vf.find("config.vm.define \"web\"").unwrap();
    assert!(cache < web, "cache starts before web, which depends on it");
    assert!(vf.contains("'10.60.0.10 web'"));
    assert!(vf.contains("virtualbox__intnet: \"isoloom-hello-stack-app\""));
}

#[test]
fn reach_rules_add_a_router_with_matching_rules() {
    let (_, spec) = example("segmented");
    let compose = &generate(&spec, Target::Docker).unwrap()[0].contents;
    assert!(compose.contains("isoloom-router:"));
    assert!(compose.contains("ipv4_address: 10.61.20.254"), "router at the last address");
    assert!(compose.contains("ip saddr 10.61.99.0/24 ip daddr 10.61.10.0/24 accept"));
    assert!(compose.contains("th dport { 6379 }"));
    assert!(compose.contains("policy drop"));
    // Routes via the router, in the machine's own network namespace.
    assert!(compose.contains("network_mode: service:web"));
    assert!(compose.contains("ip route replace 10.61.20.0/24 via 10.61.10.254"));
    // Offline machines lose their default route; no Docker-internal network with a router.
    assert!(compose.contains("ip route del default"));
    assert!(!compose.contains("internal: true"));
    // Names across networks, and checks from the access side.
    assert!(compose.contains("cache:10.61.20.20"));
    assert!(compose.contains("network_mode: service:isoloom-access"));
}

#[test]
fn vagrant_router_waits_and_offline_blocks() {
    let (_, spec) = example("segmented");
    let vf = &generate(&spec, Target::Vagrant).unwrap()[0].contents;
    let router = vf.find("config.vm.define \"isoloom-router\"").unwrap();
    let cache = vf.find("config.vm.define \"cache\"").unwrap();
    let web = vf.find("config.vm.define \"web\"").unwrap();
    assert!(router < cache && cache < web);
    assert!(vf.contains("name: \"wait for cache\""));
    assert!(vf.contains("</dev/tcp/cache/6379"));
    assert!(vf.contains("name: \"no internet\""));
    assert!(vf.contains("isoloom-routes.service"));
}

#[test]
fn unsupported_features_are_refused_with_the_reason() {
    let (_, ad) = example("corp-ad-basics");
    assert_eq!(generate(&ad, Target::Docker), Err(GenerateError::NotPossible(Target::Docker)));
    assert!(
        matches!(generate(&ad, Target::Vagrant), Err(GenerateError::Unsupported { .. })),
        "Windows has no local image yet"
    );
    assert!(
        matches!(generate(&ad, Target::Proxmox), Err(GenerateError::Unsupported { ref what, .. }) if what.contains("windows-server-2022")),
        "no Windows image on Proxmox yet"
    );
    assert_eq!(generate(&ad, Target::CloudVm), Err(GenerateError::NoGenerator(Target::CloudVm)));
}

#[test]
fn a_gateway_routes_its_networks_instead_of_the_router() {
    let (_, spec) = example("edge-firewall");
    let compose = &generate(&spec, Target::Docker).unwrap()[0].contents;
    assert!(!compose.contains("isoloom-router"), "no router: the firewall routes");
    // The firewall takes .1; Docker's bridge moves to the last address on its networks.
    assert!(compose.contains("ipv4_address: 10.70.10.1"));
    assert!(compose.contains("gateway: 10.70.10.254"));
    assert!(compose.contains("gateway: 10.70.0.1"));
    assert!(compose.contains("net.ipv4.ip_forward: '1'"));
    // Machines behind it send everything through it, once it answers.
    assert!(compose.contains("ip route replace default via 10.70.10.1"));
    assert!(compose.contains("ip route replace 10.70.10.0/24 via 10.70.0.2"));
    let web_routes = compose.split("\n  web-routes:").nth(1).unwrap().split("\n  cache:").next().unwrap();
    assert!(web_routes.contains("fw:\n        condition: service_healthy"));
    // Its own rules decide: no Docker-internal network, no route deletion.
    assert!(!compose.contains("internal: true"));
    assert!(!compose.contains("ip route del default"));
}

#[test]
fn vagrant_moves_machines_behind_their_gateway_after_provisioning() {
    let (_, spec) = example("edge-firewall");
    let vf = &generate(&spec, Target::Vagrant).unwrap()[0].contents;
    let fw = vf.find("config.vm.define \"fw\"").unwrap();
    let web = vf.find("config.vm.define \"web\"").unwrap();
    assert!(fw < web, "the gateway starts first");
    assert!(vf.contains("name: \"forwarding\""));
    let web_block = &vf[web..vf.find("config.vm.define \"cache\"").unwrap()];
    let provision = web_block.find("provision/web.sh").unwrap();
    let behind = web_block.find("name: \"through the gateway\"").unwrap();
    let default = web_block.find("ip route replace default via 10.70.10.1").unwrap();
    assert!(provision < behind && behind < default, "installs first, then moves behind the firewall");
    assert!(web_block.contains("th dport 53 accept"), "name lookups still work behind a gateway");
}

#[test]
fn networks_outside_10_move_into_10_on_docker_keeping_last_octets() {
    let spec = isoloom_core::parse(
        "version: 1\nname: t\nnetworks:\n  corp: { cidr: 192.168.20.0/24 }\n  dmz: { cidr: 172.18.5.0/24 }\n  taken: { cidr: 10.192.20.0/24 }\nmachines:\n  a: { networks: { corp: 10, dmz: 7, taken: 9 }, docker: { image: x }, vm: { os: debian-12, provision: [p.sh] } }\n",
    )
    .unwrap();
    assert_eq!(isoloom_core::validate(&spec), vec![]);
    let compose = &generate(&spec, Target::Docker).unwrap()[0].contents;
    // 172.N.X -> 10.N.X; 192.168.X -> 10.192.X, taken here, so the next free block.
    assert!(compose.contains("subnet: 10.18.5.0/24"), "{compose}");
    assert!(compose.contains("ipv4_address: 10.18.5.7"));
    assert!(compose.contains("subnet: 10.240.0.0/24"));
    assert!(compose.contains("ipv4_address: 10.240.0.10"));
    assert!(compose.contains("# On Docker, network `corp` uses 10.240.0.0/24 instead of 192.168.20.0/24"));
    // VMs keep the spec's addresses.
    let vf = &generate(&spec, Target::Vagrant).unwrap()[0].contents;
    assert!(vf.contains("ip: \"192.168.20.10\""));
}

#[test]
fn a_network_can_name_its_docker_block() {
    let base = "version: 1\nname: t\nnetworks:\n  corp: { cidr: 192.168.20.0/24, docker: { cidr: DOCKER } }\nmachines:\n  a: { networks: { corp: 10 }, docker: { image: x } }\n";
    let spec = isoloom_core::parse(&base.replace("DOCKER", "10.77.0.0/24")).unwrap();
    assert_eq!(isoloom_core::validate(&spec), vec![]);
    let compose = &generate(&spec, Target::Docker).unwrap()[0].contents;
    assert!(compose.contains("ipv4_address: 10.77.0.10"));
    for bad in ["10.77.0.0/25", "172.20.0.0/24"] {
        let p = isoloom_core::validate(&isoloom_core::parse(&base.replace("DOCKER", bad)).unwrap());
        assert!(p.iter().any(|x| x.at == "networks.corp.docker.cidr"), "{bad}: {p:?}");
    }
}

#[test]
fn windows_machines_use_winrm_and_powershell() {
    let spec = isoloom_core::parse(
        "version: 1\nname: t\nnetworks:\n  lab: { cidr: 192.168.56.0/24 }\nmachines:\n  dc01:\n    networks: { lab: 10 }\n    services: [{ port: 389 }]\n    vm:\n      os: windows-server-2019\n      provision: [provision/dc.ps1]\n  web:\n    networks: { lab: 20 }\n    depends_on: [dc01]\n    vm:\n      os: windows-server-2019\n      image: { vagrant: example/win2019, vagrant_version: '1.0' }\n      provision: [provision/web.ps1]\n",
    )
    .unwrap();
    assert_eq!(isoloom_core::validate(&spec), vec![]);
    let vf = &generate(&spec, Target::Vagrant).unwrap()[0].contents;
    let dc = &vf[vf.find("config.vm.define \"dc01\"").unwrap()..vf.find("config.vm.define \"web\"").unwrap()];
    assert!(dc.contains("m.vm.box = \"StefanScherer/windows_2019\""));
    assert!(dc.contains("m.vm.box_version = \"2021.05.15\""));
    assert!(dc.contains("m.vm.communicator = \"winrm\""));
    assert!(dc.contains("drivers\\\\etc\\\\hosts"), "the Windows hosts file: {dc}");
    assert!(dc.contains("path: File.join(ROOT, \"provision/dc.ps1\")"));
    let web = &vf[vf.find("config.vm.define \"web\"").unwrap()..];
    assert!(web.contains("m.vm.box = \"example/win2019\""), "the spec's image wins");
    assert!(web.contains("m.vm.box_version = \"1.0\""));
    assert!(web.contains("Test-NetConnection dc01 -Port $p"));
}

#[test]
fn windows_refuses_what_it_cant_do_yet() {
    let base = "version: 1\nname: t\nnetworks:\n  lab: { cidr: 10.9.0.0/24 }\nmachines:\n  NAME:\n    networks: { lab: 10 }\n    vm: { os: windows-server-2019, provision: [STEP] }\n";
    for (name, step, why) in [("dc01", "setup.yml", "PowerShell scripts"), ("averyveryverylongname", "a.ps1", "15 characters")] {
        let spec = isoloom_core::parse(&base.replace("NAME", name).replace("STEP", step)).unwrap();
        let err = generate(&spec, Target::Vagrant).unwrap_err().to_string();
        assert!(err.contains(why), "{name}: {err}");
    }
}
