//! Generators against the examples: the committed files under each example's `.isoloom/`
//! are exactly what `generate` produces (what `isoloom check` enforces in CI), and specs
//! a generator can't handle yet are refused with the reason.

use std::path::{Path, PathBuf};

use isoloom_core::{GenerateError, Target, generate, generate_all, load};

fn example(name: &str) -> (PathBuf, isoloom_core::Spec) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples").join(name);
    let spec = load(&dir).expect("example parses");
    (dir, spec)
}

fn assert_committed(name: &str) {
    let (dir, spec) = example(name);
    let (files, _) = generate_all(&spec);
    assert!(!files.is_empty(), "{name}: nothing generated");
    for f in files {
        let on_disk = std::fs::read_to_string(dir.join(&f.path)).unwrap_or_default();
        assert!(
            on_disk == f.contents,
            "{name}: {} is stale; run `cargo run -- generate examples/{name}`",
            f.path
        );
    }
}

#[test]
fn committed_outputs_are_up_to_date() {
    assert_committed("hello-stack");
    assert_committed("supplier-portal-api");
}

#[test]
fn compose_has_addresses_healthchecks_init_and_checks() {
    let (_, spec) = example("hello-stack");
    let compose = &generate(&spec, Target::Docker).unwrap()[0].contents;
    assert!(compose.contains("ipv4_address: 10.60.0.20"));
    assert!(compose.contains("gateway: 10.60.0.1"));
    assert!(compose.contains("nc -z 127.0.0.1 6379"));
    assert!(compose.contains("cache-init-1:"));
    assert!(compose.contains("condition: service_completed_successfully"));
    assert!(compose.contains("isoloom-check:"));
    assert!(compose.starts_with("# Generated by isoloom"));
}

#[test]
fn inputs_reach_only_the_machines_that_list_them() {
    let (_, spec) = example("supplier-portal-api");
    let compose = &generate(&spec, Target::Docker).unwrap()[0].contents;
    let web = compose.split("\n  web:").nth(1).unwrap().split("\n  isoloom-check:").next().unwrap();
    assert!(compose.contains("LAUNCH_TOKEN: ${LAUNCH_TOKEN:-}"));
    assert!(!web.contains("LAUNCH_TOKEN"), "web must not receive the database's inputs");
}

#[test]
fn vagrant_orders_machines_and_names_them() {
    let (_, spec) = example("hello-stack");
    let vf = &generate(&spec, Target::Vagrant).unwrap()[0].contents;
    let cache = vf.find("config.vm.define \"cache\"").unwrap();
    let web = vf.find("config.vm.define \"web\"").unwrap();
    assert!(cache < web, "cache starts before web, which depends on it");
    assert!(vf.contains("'10.60.0.10 web'"));
    assert!(vf.contains("virtualbox__intnet: \"isoloom-hello-stack-app\""));
}

#[test]
fn unsupported_features_are_refused_with_the_reason() {
    let (_, pivot) = example("pivot-dmz");
    assert!(matches!(generate(&pivot, Target::Docker), Err(GenerateError::Unsupported { .. })));
    let (_, ad) = example("corp-ad-basics");
    assert_eq!(generate(&ad, Target::Docker), Err(GenerateError::NotPossible(Target::Docker)));
    assert!(matches!(generate(&ad, Target::Vagrant), Err(GenerateError::Unsupported { .. })));
    assert_eq!(generate(&ad, Target::Proxmox), Err(GenerateError::NoGenerator(Target::Proxmox)));
}
