# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Auth:   export DIGITALOCEAN_TOKEN=<token>
# Start:  terraform -chdir=.isoloom/cloud-vm/digitalocean init && terraform -chdir=.isoloom/cloud-vm/digitalocean apply \
#           -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/digitalocean destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

variable "region" {
  type    = string
  default = "fra1"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machine (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machine up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machine down after this many minutes (0: never)"
}

provider "digitalocean" {}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name = "isoloom-solo-web-${terraform_data.id.output}"
  root = abspath("${path.module}/../../..")
}

# The environment's network: a VPC with the lab network's range. DigitalOcean assigns the
# droplet a private address in it (it can't be pinned), so this is best-effort addressing.
resource "digitalocean_vpc" "env" {
  name     = local.name
  region   = var.region
  ip_range = "10.80.0.0/24"
}

resource "digitalocean_ssh_key" "env" {
  name       = local.name
  public_key = var.ssh_public_key
}

resource "digitalocean_droplet" "web" {
  name      = "${local.name}-web"
  region    = var.region
  size      = "s-1vcpu-1gb"
  image     = "debian-12-x64"
  vpc_uuid  = digitalocean_vpc.env.id
  ssh_keys  = [digitalocean_ssh_key.env.fingerprint]
  user_data = var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : null
  tags      = ["isoloom", "solo-web"]
}

# What may reach it: SSH and the published ports from allowed_cidr, everything from the VPC.
resource "digitalocean_firewall" "web" {
  name        = local.name
  droplet_ids = [digitalocean_droplet.web.id]
  inbound_rule {
    protocol         = "tcp"
    port_range       = "22"
    source_addresses = [var.allowed_cidr]
  }
  inbound_rule {
    protocol         = "tcp"
    port_range       = "8080"
    source_addresses = [var.allowed_cidr]
  }
  inbound_rule {
    protocol         = "tcp"
    port_range       = "1-65535"
    source_addresses = [digitalocean_vpc.env.ip_range]
  }
  inbound_rule {
    protocol         = "udp"
    port_range       = "1-65535"
    source_addresses = [digitalocean_vpc.env.ip_range]
  }
  inbound_rule {
    protocol         = "icmp"
    source_addresses = [digitalocean_vpc.env.ip_range]
  }
  outbound_rule {
    protocol              = "tcp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
  outbound_rule {
    protocol              = "udp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
  outbound_rule {
    protocol              = "icmp"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
}

resource "terraform_data" "web" {
  triggers_replace = [digitalocean_droplet.web.id]
  connection {
    type        = "ssh"
    host        = digitalocean_droplet.web.ipv4_address
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown root /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-web.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project* -X \"${abspath(local_file.isoloom_project.filename)}\" -C \"${dirname(local.root)}\" \"${basename(local.root)}\""
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-web.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom --strip-components=1 && rm -f /tmp/isoloom-project.tgz",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/web.sh'",
      "command -v nft >/dev/null || (sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nftables)",
      "sudo nft add table ip isoloom-publish && sudo nft 'add chain ip isoloom-publish prerouting { type nat hook prerouting priority -100; }' && sudo nft add rule ip isoloom-publish prerouting tcp dport 8080 redirect to :80",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
}

output "machines" {
  value = {
    web = digitalocean_droplet.web.ipv4_address
  }
}

output "ssh_users" {
  value = {
    web = "root"
  }
}

output "ip" {
  value = digitalocean_droplet.web.ipv4_address
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}

output "published" {
  value = {
    "web/80" = "${digitalocean_droplet.web.ipv4_address}:8080"
  }
}

# The project's files the machines don't get: version control and the tools' state, and what
# .isoloomignore at the project's root lists (gitignore-style: one pattern per line, `#` comments,
# `!` brings a path back, a trailing `/` matches folders only, a `/` at the start or in the middle
# anchors the pattern at the root; `*`, `?`, `[abc]`, `**`; the last pattern matching a path, or
# a folder it is in, decides). Read as regular expressions, as the Vagrantfiles do.
locals {
  project_ignore_lines = [for l in split("\n", replace(try(file("${local.root}/.isoloomignore"), ""), "\r", "")) : trimspace(l)]
  project_ignore_pats  = [for l in local.project_ignore_lines : { keep = startswith(l, "!"), pat = trimprefix(l, "!") } if l != "" && !startswith(l, "#")]
  project_ignore_globs = [for r in local.project_ignore_pats : merge(r, { glob = trimsuffix(trimsuffix(trimsuffix(r.pat, "/"), "/**"), "/") })]
  project_ignore = [for r in local.project_ignore_globs : {
    keep = r.keep
    re = format(r.glob == r.pat ? "^%s(/|$)" : "^%s/", replace(replace(replace(replace(replace(replace(replace(replace(
      length(split("/", r.glob)) > 1 ? trimprefix(r.glob, "/") : "**/${r.glob}",
    "/[.+^$(){}|\\\\]/", "\\$0"), "[!", "[^"), "**/", "\u0001"), "**", "\u0002"), "*", "[^/]*"), "?", "[^/]"), "\u0001", "(.*/)?"), "\u0002", ".*"))
  } if r.glob != ""]
  # Each file: whether it goes (the last matching pattern decides; none: it goes).
  project_keep    = { for f in fileset(local.root, "**") : f => reverse(concat([true], [for r in local.project_ignore : r.keep if length(regexall(r.re, f)) > 0]))[0] }
  project_paths   = [for f, keep in local.project_keep : f if keep && length(regexall("^\\.isoloom|(^|/)\\.(git|vagrant|terraform)/", f)) == 0]
  project_ignored = [for f, keep in local.project_keep : f if !keep]
}

# What `tar` leaves out of the project's archive: .isoloomignore's files, from the archive's top
# folder, their wildcard characters escaped.
resource "local_file" "isoloom_project" {
  filename = "${path.module}/.isoloom-project-ignored.txt"
  content  = join("", [for f in local.project_ignored : "${replace("${basename(local.root)}/${f}", "/[\\\\*?\\[]/", "\\$0")}\n"])
}
