//! Generators: turn a spec into the files a target runs. Each generator is a pure function
//! of the spec (no file system access), so `isoloom check` can regenerate in memory and
//! compare with what's committed. Output lives under `.isoloom/<target>/` in the project.

mod docker;
mod router;
mod vagrant;

use std::fmt;
use std::net::Ipv4Addr;

use crate::model::{Spec, Target};
use crate::targets::effective;
use crate::validate::Cidr;

/// Where generated files go, relative to the project folder.
pub const OUTPUT_DIR: &str = ".isoloom";

/// One generated file: its path relative to the project folder, and its contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GenerateError {
    /// The spec's implementations don't allow this target (see `isoloom targets`).
    NotPossible(Target),
    /// The target is possible, but this generator doesn't support a feature the spec uses yet.
    Unsupported { target: Target, what: String },
    /// No generator exists for this target yet.
    NoGenerator(Target),
}

impl fmt::Display for GenerateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            GenerateError::NotPossible(t) => write!(f, "{}: not possible for this spec (see `isoloom targets`)", t.id()),
            GenerateError::Unsupported { target, what } => write!(f, "{}: {what}", target.id()),
            GenerateError::NoGenerator(t) => write!(f, "{}: no generator yet", t.id()),
        }
    }
}

impl std::error::Error for GenerateError {}

/// Targets that have a generator today.
pub const GENERATED_TARGETS: &[Target] = &[Target::Docker, Target::Vagrant];

/// The files for one target.
pub fn generate(spec: &Spec, target: Target) -> Result<Vec<GeneratedFile>, GenerateError> {
    if !effective(spec).contains(&target) {
        return Err(GenerateError::NotPossible(target));
    }
    match target {
        Target::Docker => docker::generate(spec),
        Target::Vagrant => vagrant::generate(spec),
        other => Err(GenerateError::NoGenerator(other)),
    }
}

/// Every target the spec allows and that has a generator: the files, and why the others
/// weren't generated.
pub fn generate_all(spec: &Spec) -> (Vec<GeneratedFile>, Vec<GenerateError>) {
    let mut files = Vec::new();
    let mut skipped = Vec::new();
    for target in effective(spec) {
        if !GENERATED_TARGETS.contains(&target) {
            skipped.push(GenerateError::NoGenerator(target));
            continue;
        }
        match generate(spec, target) {
            Ok(mut f) => files.append(&mut f),
            Err(e) => skipped.push(e),
        }
    }
    (files, skipped)
}

/// The first lines of every generated file (`comment` is the target language's marker).
fn header(comment: &str) -> String {
    format!(
        "{comment} Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run\n{comment} `isoloom generate`. `isoloom check` fails when this file is out of date.\n"
    )
}

/// A machine's address on a network (validated specs only).
fn address(spec: &Spec, network: &str, octet: u8) -> Ipv4Addr {
    let cidr = Cidr::parse(&spec.networks[network].cidr).expect("validated cidr");
    cidr.host(octet).expect("validated address")
}

/// Dotted netmask of a network.
fn netmask(spec: &Spec, network: &str) -> Ipv4Addr {
    let cidr = Cidr::parse(&spec.networks[network].cidr).expect("validated cidr");
    Ipv4Addr::from(if cidr.len == 0 { 0 } else { u32::MAX << (32 - cidr.len) })
}

/// Features no generator supports yet, shared by both (none today: kept as the place to
/// refuse a spec feature before a generator learns it).
fn common_unsupported(_spec: &Spec, _target: Target) -> Result<(), GenerateError> {
    Ok(())
}

/// Machines in start order: each after the machines it depends on (validated: no cycles).
fn start_order(spec: &Spec) -> Vec<&str> {
    let mut order: Vec<&str> = Vec::new();
    fn visit<'a>(spec: &'a Spec, name: &'a str, order: &mut Vec<&'a str>) {
        if order.contains(&name) {
            return;
        }
        for dep in &spec.machines[name].depends_on {
            visit(spec, dep, order);
        }
        order.push(name);
    }
    for name in spec.machines.keys() {
        visit(spec, name, &mut order);
    }
    order
}

/// The address `from` should use to reach `to`: on a network they share if any, else
/// `to`'s first address.
fn address_for(spec: &Spec, from: &str, to: &str) -> Ipv4Addr {
    let a = &spec.machines[from];
    let b = &spec.machines[to];
    let (net, octet) = b
        .networks
        .iter()
        .find(|(n, _)| a.networks.contains_key(*n))
        .or_else(|| b.networks.first())
        .expect("validated: machines have a network");
    address(spec, net, *octet)
}

/// A network's gateway address: `.1` of its block (reserved for it on every target).
fn gateway(spec: &Spec, network: &str) -> Ipv4Addr {
    let cidr = Cidr::parse(&spec.networks[network].cidr).expect("validated cidr");
    Ipv4Addr::from(cidr.base + 1)
}
