//! Generators: turn a spec into the files a target runs. Each generator is a pure function
//! of the spec (no file system access), so `isoloom check` can regenerate in memory and
//! compare with what's committed. Output lives under `.isoloom/<target>/` in the project.

mod cloud_docker;
mod cloud_vm;
mod docker;
mod docker_vm;
mod hybrid;
mod kubernetes;
mod proxmox;
mod router;
mod vagrant;

use std::fmt;
use std::net::Ipv4Addr;

use indexmap::IndexMap;

use crate::model::{Spec, Target};
use crate::targets::effective;
use crate::validate::Cidr;

/// Where generated files go, relative to the project folder.
pub const OUTPUT_DIR: &str = ".isoloom";

/// One generated file: its path relative to the project folder, and its contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GenerateError {
    /// The spec's implementations don't allow this target (see `isoloom targets`).
    NotPossible(Target),
    /// The target is possible, but this generator doesn't support a feature the spec uses yet.
    Unsupported { target: Target, what: String },
    /// No generator exists for this target yet.
    NoGenerator(Target),
}

impl fmt::Display for GenerateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            GenerateError::NotPossible(t) => write!(f, "{}: not possible for this spec (see `isoloom targets`)", t.id()),
            GenerateError::Unsupported { target, what } => write!(f, "{}: {what}", target.id()),
            GenerateError::NoGenerator(t) => write!(f, "{}: no generator yet", t.id()),
        }
    }
}

impl std::error::Error for GenerateError {}

/// Targets that have a generator today.
pub const GENERATED_TARGETS: &[Target] = &[
    Target::Docker,
    Target::Hosted,
    Target::DockerVm,
    Target::CloudDocker,
    Target::Kubernetes,
    Target::Hybrid,
    Target::Vagrant,
    Target::Proxmox,
    Target::CloudVm,
];

/// The files for one target.
pub fn generate(spec: &Spec, target: Target) -> Result<Vec<GeneratedFile>, GenerateError> {
    if !effective(spec).contains(&target) {
        return Err(GenerateError::NotPossible(target));
    }
    match target {
        // A hosting service runs the same Compose file.
        Target::Docker | Target::Hosted => docker::generate(&on_docker(spec), spec),
        // Docker on one VM runs the Compose file: both are generated.
        Target::CloudDocker => {
            let mut files = docker::generate(&on_docker(spec), spec)?;
            files.extend(cloud_docker::generate(spec)?);
            Ok(files)
        }
        Target::DockerVm => {
            let mut files = docker::generate(&on_docker(spec), spec)?;
            files.extend(docker_vm::generate(spec)?);
            Ok(files)
        }
        Target::Kubernetes => kubernetes::generate(spec),
        Target::Hybrid => hybrid::generate(spec),
        Target::Vagrant => vagrant::generate(spec),
        Target::Proxmox => proxmox::generate(spec),
        Target::CloudVm => cloud_vm::generate(spec),
    }
}

/// Every target the spec allows and that has a generator: the files, and why the others
/// weren't generated.
pub fn generate_all(spec: &Spec) -> (Vec<GeneratedFile>, Vec<GenerateError>) {
    let mut files = Vec::new();
    let mut skipped = Vec::new();
    for target in effective(spec) {
        if !GENERATED_TARGETS.contains(&target) {
            skipped.push(GenerateError::NoGenerator(target));
            continue;
        }
        match generate(spec, target) {
            Ok(f) => {
                // Outputs share files (docker-vm runs the Compose file): each once.
                for file in f {
                    if !files.iter().any(|x: &GeneratedFile| x.path == file.path) {
                        files.push(file);
                    }
                }
            }
            Err(e) => skipped.push(e),
        }
    }
    (files, skipped)
}

/// The first lines of every generated file (`comment` is the target language's marker).
/// The first non-access machine on arm64, if any: the cloud and Proxmox targets refuse these
/// for now (they still assume x86-64 images and instance types).
fn arm64_machine(spec: &Spec) -> Option<&str> {
    spec.machines
        .iter()
        .filter(|(_, m)| !m.access)
        .find(|(_, m)| m.arch == crate::model::Arch::Arm64)
        .map(|(n, _)| n.as_str())
}

fn header(comment: &str) -> String {
    format!(
        "{comment} Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run\n{comment} `isoloom generate`. `isoloom check` fails when this file is out of date.\n"
    )
}

/// A machine's address on a network (validated specs only).
fn address(spec: &Spec, network: &str, octet: u8) -> Ipv4Addr {
    let cidr = Cidr::parse(&spec.networks[network].cidr).expect("validated cidr");
    cidr.host(octet)
        .or_else(|| (octet == cidr.gateway_octet()).then(|| cidr.gateway()))
        .expect("validated address")
}

/// Dotted netmask of a network.
fn netmask(spec: &Spec, network: &str) -> Ipv4Addr {
    let cidr = Cidr::parse(&spec.networks[network].cidr).expect("validated cidr");
    Ipv4Addr::from(if cidr.len == 0 { 0 } else { u32::MAX << (32 - cidr.len) })
}

/// Features no generator supports yet, shared by both (none today: kept as the place to
/// refuse a spec feature before a generator learns it).
fn common_unsupported(spec: &Spec, target: Target) -> Result<(), GenerateError> {
    if target == Target::Docker && !spec.provision.is_empty() {
        return Err(GenerateError::Unsupported {
            target,
            what: "environment-level provisioning (`provision:`) runs on VM targets for now".into(),
        });
    }
    if target == Target::Docker && spec.checks.iter().any(|c| c.ends_with(".yml") || c.ends_with(".yaml")) {
        return Err(GenerateError::Unsupported {
            target,
            what: "Ansible checks (.yml) run on VM targets for now".into(),
        });
    }
    Ok(())
}

/// Machines in start order: each after the machines it depends on (validated: no cycles).
fn start_order(spec: &Spec) -> Vec<&str> {
    let mut order: Vec<&str> = Vec::new();
    fn visit<'a>(spec: &'a Spec, name: &'a str, order: &mut Vec<&'a str>) {
        if order.contains(&name) {
            return;
        }
        for dep in crate::validate::starts_after(spec, name, &spec.machines[name]) {
            visit(spec, dep, order);
        }
        order.push(name);
    }
    for name in spec.machines.keys() {
        visit(spec, name, &mut order);
    }
    order
}

/// The address `from` should use to reach `to`: on a network they share if any, else
/// `to`'s first address.
fn address_for(spec: &Spec, from: &str, to: &str) -> Ipv4Addr {
    let a = &spec.machines[from];
    let b = &spec.machines[to];
    let (net, octet) = b
        .networks
        .iter()
        .find(|(n, _)| a.networks.contains_key(*n))
        .or_else(|| b.networks.first())
        .expect("validated: machines have a network");
    address(spec, net, *octet)
}

/// The host's own address on a network (Docker's bridge): the gateway address, unless a
/// machine is the network's gateway; then the router's address, unused on such networks.
fn host_address(spec: &Spec, network: &str) -> Ipv4Addr {
    let cidr = Cidr::parse(&spec.networks[network].cidr).expect("validated cidr");
    if spec.networks[network].gateway.is_some() {
        cidr.router()
    } else {
        cidr.gateway()
    }
}

/// Each network's block on the Docker target: its `docker.cidr` when set; its `cidr` when it's
/// inside 10.0.0.0/8; otherwise moved there automatically, keeping its size (so each machine
/// keeps its last octet): 192.168.X.0 -> 10.192.X.0, 172.N.X.0 -> 10.N.X.0, or the next free
/// block when that one is taken. Validated specs only.
pub fn docker_cidrs(spec: &Spec) -> Vec<(String, Cidr)> {
    use crate::validate::DOCKER_BLOCK;
    let parse = |s: &str| Cidr::parse(s).expect("validated cidr");
    let mut fixed: Vec<(String, Cidr)> = Vec::new();
    let mut moved: Vec<(String, Cidr)> = Vec::new();
    for (name, n) in &spec.networks {
        let c = parse(&n.cidr);
        match &n.docker {
            Some(d) => fixed.push((name.clone(), parse(&d.cidr))),
            None if DOCKER_BLOCK.contains(c) => fixed.push((name.clone(), c)),
            None => moved.push((name.clone(), c)),
        }
    }
    let mut taken: Vec<Cidr> = fixed.iter().map(|(_, c)| *c).collect();
    let mut out: IndexMap<String, Cidr> = fixed.into_iter().collect();
    for (name, c) in moved {
        let [a, b, x, y] = std::net::Ipv4Addr::from(c.base).octets();
        let first = if a == 192 {
            u32::from_be_bytes([10, 192, x, y])
        } else {
            u32::from_be_bytes([10, b, x, y])
        };
        let size = 1u32 << (32 - c.len);
        // The mapped block, else the next free one of the same size scanning 10.240.0.0 upward
        // within 10.0.0.0/8. A bounded, checked successor sequence: it can't overflow, and it
        // ends at the top of the block so `find` terminates (and `expect` fires only on genuine
        // exhaustion, which needs thousands of auto-moved networks).
        let scan = std::iter::successors(Some(0x0af0_0000u32), move |&b| b.checked_add(size).filter(|&n| n <= 0x0aff_ffff));
        let candidates = std::iter::once(first).chain(scan);
        let pick = candidates
            .map(|base| Cidr { base, len: c.len })
            .find(|cand| DOCKER_BLOCK.contains(*cand) && !taken.iter().any(|t| t.overlaps(*cand)))
            .expect("10.0.0.0/8 has room for the Docker networks");
        taken.push(pick);
        out.insert(name, pick);
    }
    spec.networks.keys().map(|n| (n.clone(), out[n])).collect()
}

/// The spec as the Docker target lays it out: every network on its Docker block.
fn on_docker(spec: &Spec) -> Spec {
    let mut s = spec.clone();
    for (name, c) in docker_cidrs(spec) {
        let n = s.networks.get_mut(&name).expect("same networks");
        n.cidr = format!("{}/{}", Ipv4Addr::from(c.base), c.len);
    }
    s
}
