# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Start:  terraform -chdir=.isoloom/cloud-vm/gcp init && terraform -chdir=.isoloom/cloud-vm/gcp apply \
#           -var billing_account=<id> -var allowed_cidr=<your IP>/32 -var ssh_public_key="$(cat ~/.ssh/id_ed25519.pub)" -var ssh_private_key_file=~/.ssh/id_ed25519
# Stop:   terraform -chdir=.isoloom/cloud-vm/gcp destroy (same variables)

terraform {
  required_version = ">= 1.6"
  backend "local" {}
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 8.0"
    }
  }
}

variable "project" {
  type        = string
  default     = ""
  description = "An existing project; or leave empty and give billing_account for a project of its own"
}
variable "billing_account" {
  type        = string
  default     = ""
  description = "With no project: create one for this environment, billed here, deleted with it"
}
variable "org_id" {
  type    = string
  default = ""
}
variable "region" {
  type    = string
  default = "europe-west1"
}
variable "allowed_cidr" {
  type        = string
  description = "Who may reach the machines (SSH and the published ports), e.g. your IP/32"
}
variable "ssh_public_key" {
  type = string
}
variable "ssh_private_key_file" {
  type        = string
  description = "The private key of ssh_public_key: Terraform sets the machines up over SSH"
}
variable "auto_stop_minutes" {
  type        = number
  default     = 0
  description = "Shut the machines down after this many minutes (0: never)"
}

provider "google" {
  region = var.region
}

# A project of its own when none is given: everything goes when the environment is destroyed.
resource "google_project" "env" {
  count               = var.project == "" ? 1 : 0
  name                = "isoloom-air-gapped"
  project_id          = "isoloom-${terraform_data.id.output}"
  billing_account     = var.billing_account
  org_id              = var.org_id == "" ? null : var.org_id
  deletion_policy     = "DELETE"
  auto_create_network = false
}

resource "google_project_service" "compute" {
  count              = var.project == "" ? 1 : 0
  project            = google_project.env[0].project_id
  service            = "compute.googleapis.com"
  disable_on_destroy = false
}

resource "terraform_data" "id" {
  input = substr(replace(uuid(), "-", ""), 0, 8)
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  name    = "isoloom-air-gapped-${terraform_data.id.output}"
  root    = abspath("${path.module}/../../..")
  project = var.project != "" ? var.project : google_project_service.compute[0].project
  zone    = "${var.region}-a"
}

# The environment's networks: one VPC, a subnetwork per network with its exact range.
resource "google_compute_network" "env" {
  project                 = local.project
  name                    = local.name
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "lab" {
  project       = local.project
  name          = "${local.name}-lab"
  network       = google_compute_network.env.id
  ip_cidr_range = "192.168.62.0/24"
  region        = var.region
}

# Machine `store`: what may reach it.
resource "google_compute_firewall" "store_net" {
  project       = local.project
  name          = "${local.name}-store-net"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = ["192.168.62.0/24"]
  target_tags   = ["${local.name}-store"]
  allow {
    protocol = "all"
  }
}

resource "google_compute_firewall" "store_ssh" {
  project       = local.project
  name          = "${local.name}-store-ssh"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = [var.allowed_cidr]
  target_tags   = ["${local.name}-store"]
  allow {
    protocol = "tcp"
    ports    = ["22"]
  }
}

resource "google_compute_instance" "store" {
  project      = local.project
  name         = "${local.name}-store"
  machine_type = "e2-small"
  zone         = local.zone
  tags         = ["${local.name}-store"]
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 20
    }
  }
  network_interface {
    subnetwork = google_compute_subnetwork.lab.id
    network_ip = "192.168.62.20"
    access_config {}
  }
  metadata = {
    ssh-keys = "admin:${var.ssh_public_key}"
  }
  metadata_startup_script = var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : null
  labels = {
    "isoloom-environment" = "air-gapped"
    "managed-by"          = "isoloom"
  }
}

resource "terraform_data" "store" {
  triggers_replace = [google_compute_instance.store.id]
  connection {
    type        = "ssh"
    host        = google_compute_instance.store.network_interface[0].access_config[0].nat_ip
    user        = "admin"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown admin /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-store.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-store.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '192.168.62.10 app' | sudo tee -a /etc/hosts >/dev/null",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/store.sh'",
      "command -v nft >/dev/null || (sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nftables)",
      "printf '%s\\n' 'table inet isoloom-egress {' '  chain output {' '    type filter hook output priority 0; policy accept;' '    ip daddr != { 192.168.62.0/24 } ct state new drop' '  }' '}' | sudo tee /etc/isoloom-egress.nft >/dev/null && sudo nft -f /etc/isoloom-egress.nft",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
}

# Machine `app`: what may reach it.
resource "google_compute_firewall" "app_net" {
  project       = local.project
  name          = "${local.name}-app-net"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = ["192.168.62.0/24"]
  target_tags   = ["${local.name}-app"]
  allow {
    protocol = "all"
  }
}

resource "google_compute_firewall" "app_ssh" {
  project       = local.project
  name          = "${local.name}-app-ssh"
  network       = google_compute_network.env.id
  direction     = "INGRESS"
  source_ranges = [var.allowed_cidr]
  target_tags   = ["${local.name}-app"]
  allow {
    protocol = "tcp"
    ports    = ["22"]
  }
}

resource "google_compute_instance" "app" {
  project      = local.project
  name         = "${local.name}-app"
  machine_type = "e2-small"
  zone         = local.zone
  tags         = ["${local.name}-app"]
  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 20
    }
  }
  network_interface {
    subnetwork = google_compute_subnetwork.lab.id
    network_ip = "192.168.62.10"
    access_config {}
  }
  metadata = {
    ssh-keys = "admin:${var.ssh_public_key}"
  }
  metadata_startup_script = var.auto_stop_minutes > 0 ? "#!/bin/sh\nshutdown -h +${var.auto_stop_minutes}\n" : null
  labels = {
    "isoloom-environment" = "air-gapped"
    "managed-by"          = "isoloom"
  }
}

resource "terraform_data" "app" {
  triggers_replace = [google_compute_instance.app.id]
  connection {
    type        = "ssh"
    host        = google_compute_instance.app.network_interface[0].access_config[0].nat_ip
    user        = "admin"
    private_key = file(pathexpand(var.ssh_private_key_file))
    timeout     = "10m"
  }
  provisioner "remote-exec" {
    inline = ["cloud-init status --wait >/dev/null 2>&1 || true", "sudo mkdir -p /opt/isoloom && sudo chown admin /opt/isoloom"]
  }
  provisioner "local-exec" {
    command = "tar -czf \"${path.module}/.isoloom-project-app.tgz\" --exclude=.git --exclude=.vagrant --exclude=.terraform --exclude=.isoloom-project*.tgz -C \"${local.root}\" ."
  }
  provisioner "file" {
    source      = "${path.module}/.isoloom-project-app.tgz"
    destination = "/tmp/isoloom-project.tgz"
  }
  provisioner "remote-exec" {
    inline = [
      "set -e",
      "cloud-init status --wait >/dev/null 2>&1 || true",
      "tar -xzf /tmp/isoloom-project.tgz -C /opt/isoloom && rm -f /tmp/isoloom-project.tgz",
      "printf '%s\\n' '192.168.62.20 store' | sudo tee -a /etc/hosts >/dev/null",
      "sh -c 'i=0; until (bash -c '\\''</dev/tcp/store/6379'\\'' 2>/dev/null || nc -z -w 2 store 6379 2>/dev/null); do i=$((i+2)); if [ $i -ge 900 ]; then echo \"store didn'\\''t answer within 900s\" >&2; exit 1; fi; sleep 2; done; echo \"store answers\"'",
      "cd /opt/isoloom && sudo -E sh -c 'sh provision/app.sh'",
      "command -v nft >/dev/null || (sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nftables)",
      "printf '%s\\n' 'table inet isoloom-egress {' '  chain output {' '    type filter hook output priority 0; policy accept;' '    ip daddr != { 192.168.62.0/24 } ct state new drop' '  }' '}' | sudo tee /etc/isoloom-egress.nft >/dev/null && sudo nft -f /etc/isoloom-egress.nft",
      "sudo mkdir -p /var/lib/isoloom && echo ready | sudo tee /var/lib/isoloom/ready >/dev/null"
    ]
  }
  depends_on = [terraform_data.store]
}

output "machines" {
  value = {
    store = google_compute_instance.store.network_interface[0].access_config[0].nat_ip
    app   = google_compute_instance.app.network_interface[0].access_config[0].nat_ip
  }
}

output "ssh_users" {
  value = {
    store = "admin"
    app   = "admin"
  }
}

output "ip" {
  value = google_compute_instance.store.network_interface[0].access_config[0].nat_ip
}

output "ready_file" {
  value = "/var/lib/isoloom/ready"
}

# The checks, from where a user stands: ssh <user>@<host> each command.
output "checks" {
  value = {
    host = google_compute_instance.store.network_interface[0].access_config[0].nat_ip
    user = null
    commands = [
      "cd /opt/isoloom && sh checks/app-answers.sh",
      "cd /opt/isoloom && sh checks/no-internet.sh"
    ]
  }
}
